In [20]:
#load 
from pathlib import Path
import subprocess
import pandas as pd
import tempfile
import os

OpenSMILE, intensity 3 dB

In [21]:
# paths
BASE_DIR = Path(r"C:\Users\marti\Documents\Technical Medicine Master\Stages TM2\TM2-3\Technische opdracht")

OPENSMILE_EXE = BASE_DIR / "tools" / "openSMILE" / "bin" / "SMILExtract.exe"
CONFIG_FILE = BASE_DIR / "tools" / "openSMILE" / "config" / "egemaps" / "v02" / "eGeMAPSv02.conf"

AUDIO_ROOT = BASE_DIR / "TAME" / "wiener_intensity_perturbations_pain" / "+3dB"

OUTPUT_FEATURES_CSV = BASE_DIR / "opensmile_intensity_3dB_features_pain.csv"
OUTPUT_FAILED_CSV = BASE_DIR / "opensmile_intensity_3dB_failed_files.csv"

# check
print("SMILExtract exists:", OPENSMILE_EXE.exists())
print("Config exists:", CONFIG_FILE.exists())
print("Audio root exists:", AUDIO_ROOT.exists())

if not OPENSMILE_EXE.exists():
    raise FileNotFoundError(f"SMILExtract.exe not found:\n{OPENSMILE_EXE}")

if not CONFIG_FILE.exists():
    raise FileNotFoundError(f"Config file not found:\n{CONFIG_FILE}")

if not AUDIO_ROOT.exists():
    raise FileNotFoundError(f"Audio root not found:\n{AUDIO_ROOT}")

#WAV files
wav_files = sorted(AUDIO_ROOT.rglob("*.wav"))
print(f"Number of wav. files found: {len(wav_files)}")

if len(wav_files) == 0:
    raise ValueError("no .wav files found.")

# Run OpenSMILE
all_rows = []
failed_files = []

for i, wav_file in enumerate(wav_files, start=1):
    print(f"[{i}/{len(wav_files)}] Processing: {wav_file.name}")

    participant_id = wav_file.parent.name
    filename = wav_file.name

    with tempfile.NamedTemporaryFile(suffix=".csv", delete=False) as tmp:
        temp_output_csv = Path(tmp.name)

    try:
        if temp_output_csv.exists():
            temp_output_csv.unlink(missing_ok=True)

        cmd = [
            str(OPENSMILE_EXE),
            "-C", str(CONFIG_FILE),
            "-I", str(wav_file),
            "-csvoutput", str(temp_output_csv),
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode != 0:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "openSMILE return code != 0",
                "stderr": result.stderr
            })
            continue

        if not temp_output_csv.exists():
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "no output made",
                "stderr": result.stderr
            })
            continue

        try:
            feature_df = pd.read_csv(temp_output_csv, sep=";", engine="python")
        except Exception as e:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": f"error in csv: {e}",
                "stderr": result.stderr
            })
            continue

        if feature_df.empty:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "Output csv is leeg",
                "stderr": result.stderr
            })
            continue

        #adding information 
        row = feature_df.iloc[0].to_dict()
        row["name"] = filename
        row["participant_id"] = participant_id
        row["filename"] = filename
        row["file_path"] = str(wav_file)

        all_rows.append(row)

    except Exception as e:
        failed_files.append({
            "participant_id": participant_id,
            "filename": filename,
            "file_path": str(wav_file),
            "reason": f"error {e}",
            "stderr": ""
        })

    finally:
        if temp_output_csv.exists():
            temp_output_csv.unlink(missing_ok=True)


#Save
features_df = pd.DataFrame(all_rows)

# Kolommen netjes ordenen
preferred_front_cols = ["participant_id", "filename", "file_path", "name", "frameTime"]
remaining_cols = [col for col in features_df.columns if col not in preferred_front_cols]
features_df = features_df[[col for col in preferred_front_cols if col in features_df.columns] + remaining_cols]

features_df.to_csv(OUTPUT_FEATURES_CSV, index=False)

print("\nKlaar.")
print("number of errors in features:", len(features_df))
print("numer of errors in the files:", len(failed_files))
print("Features saves in :")
print(OUTPUT_FEATURES_CSV)

if failed_files:
    failed_df = pd.DataFrame(failed_files)
    failed_df.to_csv(OUTPUT_FAILED_CSV, index=False)
    print("\n errors saved:")
    print(OUTPUT_FAILED_CSV)


# Results
print("\nShape features dataframe:", features_df.shape)
display(features_df.head())

SMILExtract exists: True
Config exists: True
Audio root exists: True
Number of wav. files found: 1005
[1/1005] Processing: p10085.LC.1.161.wav
[2/1005] Processing: p10085.LC.12.59.wav
[3/1005] Processing: p10085.LC.14.45.wav
[4/1005] Processing: p10085.LC.18.41.wav
[5/1005] Processing: p10085.LC.2.106.wav
[6/1005] Processing: p10085.LC.23.156.wav
[7/1005] Processing: p10085.LC.24.172.wav
[8/1005] Processing: p10085.LC.26.99999.wav
[9/1005] Processing: p10085.LC.3.60.wav
[10/1005] Processing: p10085.LC.30.132.wav
[11/1005] Processing: p10085.LC.31.99999.wav
[12/1005] Processing: p10085.LC.33.6.wav
[13/1005] Processing: p10085.LC.34.122.wav
[14/1005] Processing: p10085.LC.37.71.wav
[15/1005] Processing: p10085.LC.38.160.wav
[16/1005] Processing: p10085.LC.4.76.wav
[17/1005] Processing: p10085.LC.40.174.wav
[18/1005] Processing: p10085.LC.41.99999.wav
[19/1005] Processing: p10085.LC.5.134.wav
[20/1005] Processing: p10085.LC.6.99999.wav
[21/1005] Processing: p10085.LC.9.55.wav
[22/1005] Processing: p10085.LW.28.85.wav
[23/1005] Processing: p10085.LW.36.99999.wav
[24/1005] Processing: p10085.RC.11.99999.wav
[25/1005] Processing: p10085.RC.12.165.wav
[26/1005] Processing: p10085.RC.13.36.wav
[27/1005] Processing: p10085.RC.14.86.wav
[28/1005] Processing: p10085.RC.16.99999.wav
[29/1005] Processing: p10085.RC.17.160.wav
[30/1005] Processing: p10085.RC.19.78.wav
[31/1005] Processing: p10085.RC.26.99999.wav
[32/1005] Processing: p10085.RC.28.52.wav
[33/1005] Processing: p10085.RC.29.182.wav
[34/1005] Processing: p10085.RC.3.58.wav
[35/1005] Processing: p10085.RC.30.53.wav
[36/1005] Processing: p10085.RC.31.99999.wav
[37/1005] Processing: p10085.RC.32.24.wav
[38/1005] Processing: p10085.RC.33.126.wav
[39/1005] Processing: p10085.RC.34.18.wav
[40/1005] Processing: p10085.RC.35.75.wav
[41/1005] Processing: p10085.RC.36.99999.wav
[42/1005] Processing: p10085.RC.8.50.wav
[43/1005] Processing: p10085.RC.9.85.wav
[44/1005] Processing: p15965.LC.10.146.wav
[45/1005] Processing: p15965.LC.11.99999.wav
[46/1005] Processing: p15965.LC.12.161.wav
[47/1005] Processing: p15965.LC.13.83.wav
[48/1005] Processing: p15965.LC.14.48.wav
[49/1005] Processing: p15965.LC.15.182.wav
[50/1005] Processing: p15965.LC.17.164.wav
[51/1005] Processing: p15965.LC.18.143.wav
[52/1005] Processing: p15965.LC.19.131.wav
[53/1005] Processing: p15965.LC.2.118.wav
[54/1005] Processing: p15965.LC.20.10.wav
[55/1005] Processing: p15965.LC.21.99999.wav
[56/1005] Processing: p15965.LC.23.178.wav
[57/1005] Processing: p15965.LC.24.36.wav
[58/1005] Processing: p15965.LC.26.99999.wav
[59/1005] Processing: p15965.LC.29.1.wav
[60/1005] Processing: p15965.LC.3.45.wav
[61/1005] Processing: p15965.LC.30.123.wav
[62/1005] Processing: p15965.LC.31.99999.wav
[63/1005] Processing: p15965.LC.32.30.wav
[64/1005] Processing: p15965.LC.33.46.wav
[65/1005] Processing: p15965.LC.34.147.wav
[66/1005] Processing: p15965.LC.35.155.wav
[67/1005] Processing: p15965.LC.36.99999.wav
[68/1005] Processing: p15965.LC.38.63.wav
[69/1005] Processing: p15965.LC.4.81.wav
[70/1005] Processing: p15965.LC.41.99999.wav
[71/1005] Processing: p15965.LC.5.163.wav
[72/1005] Processing: p15965.LC.6.99999.wav
[73/1005] Processing: p15965.LC.7.66.wav
[74/1005] Processing: p15965.LC.9.129.wav
[75/1005] Processing: p15965.LW.11.99999.wav
[76/1005] Processing: p15965.LW.12.45.wav
[77/1005] Processing: p15965.LW.13.41.wav
[78/1005] Processing: p15965.LW.16.99999.wav
[79/1005] Processing: p15965.LW.17.134.wav
[80/1005] Processing: p15965.LW.18.118.wav
[81/1005] Processing: p15965.LW.19.67.wav
[82/1005] Processing: p15965.LW.2.155.wav
[83/1005] Processing: p15965.LW.20.63.wav
[84/1005] Processing: p15965.LW.21.99999.wav
[85/1005] Processing: p15965.LW.23.29.wav
[86/1005] Processing: p15965.LW.24.83.wav
[87/1005] Processing: p15965.LW.25.102.wav
[88/1005] Processing: p15965.LW.26.99999.wav
[89/1005] Processing: p15965.LW.27.36.wav
[90/1005] Processing: p15965.LW.28.69.wav
[91/1005] Processing: p15965.LW.3.122.wav
[92/1005] Processing: p15965.LW.30.163.wav
[93/1005] Processing: p15965.LW.31.99999.wav
[94/1005] Processing: p15965.LW.32.137.wav
[95/1005] Processing: p15965.LW.33.4.wav
[96/1005] Processing: p15965.LW.34.170.wav
[97/1005] Processing: p15965.LW.35.43.wav
[98/1005] Processing: p15965.LW.36.99999.wav
[99/1005] Processing: p15965.LW.37.138.wav
[100/1005] Processing: p15965.LW.38.47.wav
[101/1005] Processing: p15965.LW.39.65.wav
[102/1005] Processing: p15965.LW.4.116.wav
[103/1005] Processing: p15965.LW.40.95.wav
[104/1005] Processing: p15965.LW.41.99999.wav
[105/1005] Processing: p15965.LW.5.172.wav
[106/1005] Processing: p15965.LW.6.99999.wav
[107/1005] Processing: p15965.LW.7.153.wav
[108/1005] Processing: p15965.LW.8.32.wav
[109/1005] Processing: p15965.LW.9.160.wav
[110/1005] Processing: p15965.RC.1.44.wav
[111/1005] Processing: p15965.RC.10.155.wav
[112/1005] Processing: p15965.RC.11.99999.wav
[113/1005] Processing: p15965.RC.12.28.wav
[114/1005] Processing: p15965.RC.13.105.wav
[115/1005] Processing: p15965.RC.14.185.wav
[116/1005] Processing: p15965.RC.15.125.wav
[117/1005] Processing: p15965.RC.16.99999.wav
[118/1005] Processing: p15965.RC.17.47.wav
[119/1005] Processing: p15965.RC.18.56.wav
[120/1005] Processing: p15965.RC.19.31.wav
[121/1005] Processing: p15965.RC.2.121.wav
[122/1005] Processing: p15965.RC.20.99.wav
[123/1005] Processing: p15965.RC.21.99999.wav
[124/1005] Processing: p15965.RC.22.158.wav
[125/1005] Processing: p15965.RC.23.37.wav
[126/1005] Processing: p15965.RC.24.2.wav
[127/1005] Processing: p15965.RC.25.154.wav
[128/1005] Processing: p15965.RC.27.18.wav
[129/1005] Processing: p15965.RC.29.120.wav
[130/1005] Processing: p15965.RC.30.42.wav
[131/1005] Processing: p15965.RC.31.99999.wav
[132/1005] Processing: p15965.RC.32.76.wav
[133/1005] Processing: p15965.RC.33.104.wav
[134/1005] Processing: p15965.RC.34.39.wav
[135/1005] Processing: p15965.RC.35.72.wav
[136/1005] Processing: p15965.RC.36.99999.wav
[137/1005] Processing: p15965.RC.37.68.wav
[138/1005] Processing: p15965.RC.38.137.wav
[139/1005] Processing: p15965.RC.39.24.wav
[140/1005] Processing: p15965.RC.4.136.wav
[141/1005] Processing: p15965.RC.41.99999.wav
[142/1005] Processing: p15965.RC.5.53.wav
[143/1005] Processing: p15965.RC.6.99999.wav
[144/1005] Processing: p15965.RC.7.135.wav
[145/1005] Processing: p15965.RC.8.117.wav
[146/1005] Processing: p15965.RW.1.39.wav
[147/1005] Processing: p15965.RW.10.2.wav
[148/1005] Processing: p15965.RW.11.99999.wav
[149/1005] Processing: p15965.RW.12.61.wav
[150/1005] Processing: p15965.RW.14.112.wav
[151/1005] Processing: p15965.RW.15.106.wav
[152/1005] Processing: p15965.RW.17.183.wav
[153/1005] Processing: p15965.RW.18.151.wav
[154/1005] Processing: p15965.RW.19.140.wav
[155/1005] Processing: p15965.RW.2.181.wav
[156/1005] Processing: p15965.RW.20.161.wav
[157/1005] Processing: p15965.RW.21.99999.wav
[158/1005] Processing: p15965.RW.22.168.wav
[159/1005] Processing: p15965.RW.23.153.wav
[160/1005] Processing: p15965.RW.24.44.wav
[161/1005] Processing: p15965.RW.25.159.wav
[162/1005] Processing: p15965.RW.27.117.wav
[163/1005] Processing: p15965.RW.28.0.wav
[164/1005] Processing: p15965.RW.29.156.wav
[165/1005] Processing: p15965.RW.3.115.wav
[166/1005] Processing: p15965.RW.30.178.wav
[167/1005] Processing: p15965.RW.32.149.wav
[168/1005] Processing: p15965.RW.33.30.wav
[169/1005] Processing: p15965.RW.34.167.wav
[170/1005] Processing: p15965.RW.35.74.wav
[171/1005] Processing: p15965.RW.36.99999.wav
[172/1005] Processing: p15965.RW.37.67.wav
[173/1005] Processing: p15965.RW.38.76.wav
[174/1005] Processing: p15965.RW.39.137.wav
[175/1005] Processing: p15965.RW.4.68.wav
[176/1005] Processing: p15965.RW.40.107.wav
[177/1005] Processing: p15965.RW.41.99999.wav
[178/1005] Processing: p15965.RW.5.42.wav
[179/1005] Processing: p15965.RW.8.65.wav
[180/1005] Processing: p15965.RW.9.49.wav
[181/1005] Processing: p18785.LC.1.123.wav
[182/1005] Processing: p18785.LC.13.38.wav
[183/1005] Processing: p18785.LC.14.143.wav
[184/1005] Processing: p18785.LC.4.100.wav
[185/1005] Processing: p18785.LC.6.99999.wav
[186/1005] Processing: p18785.LC.7.13.wav
[187/1005] Processing: p18785.LC.8.175.wav
[188/1005] Processing: p18785.LW.11.99999.wav
[189/1005] Processing: p18785.LW.19.97.wav
[190/1005] Processing: p18785.RC.1.31.wav
[191/1005] Processing: p18785.RC.12.77.wav
[192/1005] Processing: p18785.RC.13.18.wav
[193/1005] Processing: p18785.RC.15.96.wav
[194/1005] Processing: p18785.RC.2.187.wav
[195/1005] Processing: p18785.RC.3.103.wav
[196/1005] Processing: p18785.RC.4.63.wav
[197/1005] Processing: p18785.RC.5.24.wav
[198/1005] Processing: p18785.RW.12.58.wav
[199/1005] Processing: p18785.RW.15.165.wav
[200/1005] Processing: p18785.RW.16.99999.wav
[201/1005] Processing: p18785.RW.19.131.wav
[202/1005] Processing: p18785.RW.21.99999.wav
[203/1005] Processing: p18785.RW.26.99999.wav
[204/1005] Processing: p18785.RW.28.102.wav
[205/1005] Processing: p18785.RW.9.5.wav
[206/1005] Processing: p20960.LC.1.185.wav
[207/1005] Processing: p20960.LC.11.99999.wav
[208/1005] Processing: p20960.LC.12.92.wav
[209/1005] Processing: p20960.LC.13.43.wav
[210/1005] Processing: p20960.LC.14.18.wav
[211/1005] Processing: p20960.LC.15.141.wav
[212/1005] Processing: p20960.LC.19.6.wav
[213/1005] Processing: p20960.LC.2.84.wav
[214/1005] Processing: p20960.LC.20.120.wav
[215/1005] Processing: p20960.LC.23.37.wav
[216/1005] Processing: p20960.LC.24.25.wav
[217/1005] Processing: p20960.LC.27.140.wav
[218/1005] Processing: p20960.LC.28.83.wav
[219/1005] Processing: p20960.LC.29.182.wav
[220/1005] Processing: p20960.LC.3.40.wav
[221/1005] Processing: p20960.LC.30.128.wav
[222/1005] Processing: p20960.LC.31.99999.wav
[223/1005] Processing: p20960.LC.32.151.wav
[224/1005] Processing: p20960.LC.33.137.wav
[225/1005] Processing: p20960.LC.34.176.wav
[226/1005] Processing: p20960.LC.35.186.wav
[227/1005] Processing: p20960.LC.6.99999.wav
[228/1005] Processing: p20960.LC.7.1.wav
[229/1005] Processing: p20960.LW.19.31.wav
[230/1005] Processing: p20960.LW.5.165.wav
[231/1005] Processing: p20960.RC.13.88.wav
[232/1005] Processing: p20960.RC.16.99999.wav
[233/1005] Processing: p20960.RC.17.77.wav
[234/1005] Processing: p20960.RC.19.104.wav
[235/1005] Processing: p20960.RC.20.178.wav
[236/1005] Processing: p20960.RC.22.33.wav
[237/1005] Processing: p20960.RC.23.47.wav
[238/1005] Processing: p20960.RC.25.63.wav
[239/1005] Processing: p20960.RC.26.99999.wav
[240/1005] Processing: p20960.RC.27.56.wav
[241/1005] Processing: p20960.RC.28.58.wav
[242/1005] Processing: p20960.RC.30.143.wav
[243/1005] Processing: p20960.RC.31.99999.wav
[244/1005] Processing: p20960.RC.32.109.wav
[245/1005] Processing: p20960.RC.33.22.wav
[246/1005] Processing: p20960.RC.35.121.wav
[247/1005] Processing: p20960.RC.5.16.wav
[248/1005] Processing: p20960.RC.7.142.wav
[249/1005] Processing: p20960.RW.10.17.wav
[250/1005] Processing: p20960.RW.25.88.wav
[251/1005] Processing: p28030.LC.10.63.wav
[252/1005] Processing: p28030.LC.2.59.wav
[253/1005] Processing: p28030.LC.20.17.wav
[254/1005] Processing: p28030.LC.3.133.wav
[255/1005] Processing: p28030.LC.31.99999.wav
[256/1005] Processing: p28030.LC.5.23.wav
[257/1005] Processing: p28030.LC.7.86.wav
[258/1005] Processing: p28030.LC.8.188.wav
[259/1005] Processing: p28030.LC.9.12.wav
[260/1005] Processing: p28030.LW.15.107.wav
[261/1005] Processing: p28030.LW.16.99999.wav
[262/1005] Processing: p28030.LW.18.53.wav
[263/1005] Processing: p28030.LW.20.50.wav
[264/1005] Processing: p28030.RC.1.86.wav
[265/1005] Processing: p28030.RC.13.22.wav
[266/1005] Processing: p28030.RC.18.45.wav
[267/1005] Processing: p28030.RC.19.51.wav
[268/1005] Processing: p28030.RC.26.99999.wav
[269/1005] Processing: p28030.RC.29.39.wav
[270/1005] Processing: p28030.RC.3.7.wav
[271/1005] Processing: p28030.RC.30.118.wav
[272/1005] Processing: p28030.RC.33.152.wav
[273/1005] Processing: p28030.RC.36.99999.wav
[274/1005] Processing: p28030.RC.4.66.wav
[275/1005] Processing: p28030.RC.5.178.wav
[276/1005] Processing: p28030.RC.6.99999.wav
[277/1005] Processing: p28030.RW.13.175.wav
[278/1005] Processing: p28030.RW.16.99999.wav
[279/1005] Processing: p28030.RW.28.177.wav
[280/1005] Processing: p37540.LC.10.24.wav
[281/1005] Processing: p37540.LC.14.32.wav
[282/1005] Processing: p37540.LC.15.185.wav
[283/1005] Processing: p37540.LC.17.128.wav
[284/1005] Processing: p37540.LC.20.67.wav
[285/1005] Processing: p37540.LC.25.121.wav
[286/1005] Processing: p37540.LC.29.87.wav
[287/1005] Processing: p37540.LC.31.99999.wav
[288/1005] Processing: p37540.LC.33.166.wav
[289/1005] Processing: p37540.LC.34.30.wav
[290/1005] Processing: p37540.LC.35.48.wav
[291/1005] Processing: p37540.LC.36.99999.wav
[292/1005] Processing: p37540.LC.4.90.wav
[293/1005] Processing: p37540.LC.9.112.wav
[294/1005] Processing: p37540.LW.15.168.wav
[295/1005] Processing: p37540.LW.21.99999.wav
[296/1005] Processing: p37540.RC.11.99999.wav
[297/1005] Processing: p37540.RC.16.99999.wav
[298/1005] Processing: p37540.RC.17.131.wav
[299/1005] Processing: p37540.RC.18.186.wav
[300/1005] Processing: p37540.RC.21.99999.wav
[301/1005] Processing: p37540.RC.22.138.wav
[302/1005] Processing: p37540.RC.27.35.wav
[303/1005] Processing: p37540.RC.28.187.wav
[304/1005] Processing: p37540.RC.29.154.wav
[305/1005] Processing: p37540.RC.3.182.wav
[306/1005] Processing: p37540.RC.30.91.wav
[307/1005] Processing: p37540.RC.31.99999.wav
[308/1005] Processing: p37540.RC.32.119.wav
[309/1005] Processing: p37540.RC.33.93.wav
[310/1005] Processing: p37540.RC.36.99999.wav
[311/1005] Processing: p37540.RC.4.36.wav
[312/1005] Processing: p37540.RC.5.89.wav
[313/1005] Processing: p37540.RW.10.18.wav
[314/1005] Processing: p37540.RW.13.0.wav
[315/1005] Processing: p37540.RW.16.99999.wav
[316/1005] Processing: p37540.RW.25.135.wav
[317/1005] Processing: p37540.RW.36.99999.wav
[318/1005] Processing: p37540.RW.6.99999.wav
[319/1005] Processing: p37540.RW.9.30.wav
[320/1005] Processing: p59520.LC.1.148.wav
[321/1005] Processing: p59520.LC.10.66.wav
[322/1005] Processing: p59520.LC.12.181.wav
[323/1005] Processing: p59520.LC.13.107.wav
[324/1005] Processing: p59520.LC.14.153.wav
[325/1005] Processing: p59520.LC.15.47.wav
[326/1005] Processing: p59520.LC.16.99999.wav
[327/1005] Processing: p59520.LC.19.101.wav
[328/1005] Processing: p59520.LC.2.60.wav
[329/1005] Processing: p59520.LC.20.177.wav
[330/1005] Processing: p59520.LC.22.152.wav
[331/1005] Processing: p59520.LC.27.33.wav
[332/1005] Processing: p59520.LC.29.63.wav
[333/1005] Processing: p59520.LC.3.86.wav
[334/1005] Processing: p59520.LC.30.114.wav
[335/1005] Processing: p59520.LC.36.99999.wav
[336/1005] Processing: p59520.LC.4.137.wav
[337/1005] Processing: p59520.LC.5.140.wav
[338/1005] Processing: p59520.LC.6.99999.wav
[339/1005] Processing: p59520.LC.7.186.wav
[340/1005] Processing: p59520.LW.14.72.wav
[341/1005] Processing: p59520.LW.35.136.wav
[342/1005] Processing: p59520.LW.8.17.wav
[343/1005] Processing: p59520.RC.1.121.wav
[344/1005] Processing: p59520.RC.11.99999.wav
[345/1005] Processing: p59520.RC.12.8.wav
[346/1005] Processing: p59520.RC.14.162.wav
[347/1005] Processing: p59520.RC.2.156.wav
[348/1005] Processing: p59520.RC.21.99999.wav
[349/1005] Processing: p59520.RC.22.10.wav
[350/1005] Processing: p59520.RC.23.34.wav
[351/1005] Processing: p59520.RC.24.58.wav
[352/1005] Processing: p59520.RC.25.126.wav
[353/1005] Processing: p59520.RC.26.99999.wav
[354/1005] Processing: p59520.RC.28.57.wav
[355/1005] Processing: p59520.RC.29.184.wav
[356/1005] Processing: p59520.RC.3.13.wav
[357/1005] Processing: p59520.RC.32.30.wav
[358/1005] Processing: p59520.RC.33.71.wav
[359/1005] Processing: p59520.RC.34.174.wav
[360/1005] Processing: p59520.RC.35.76.wav
[361/1005] Processing: p59520.RC.36.99999.wav
[362/1005] Processing: p59520.RC.4.47.wav
[363/1005] Processing: p59520.RC.5.112.wav
[364/1005] Processing: p59520.RC.7.95.wav
[365/1005] Processing: p59520.RC.9.166.wav
[366/1005] Processing: p59520.RW.10.82.wav
[367/1005] Processing: p59520.RW.16.99999.wav
[368/1005] Processing: p59520.RW.17.74.wav
[369/1005] Processing: p59520.RW.24.130.wav
[370/1005] Processing: p59520.RW.25.79.wav
[371/1005] Processing: p59520.RW.3.66.wav
[372/1005] Processing: p59520.RW.34.156.wav
[373/1005] Processing: p60145.LC.11.99999.wav
[374/1005] Processing: p60145.LC.12.31.wav
[375/1005] Processing: p60145.LC.14.50.wav
[376/1005] Processing: p60145.LC.15.147.wav
[377/1005] Processing: p60145.LC.16.99999.wav
[378/1005] Processing: p60145.LC.17.32.wav
[379/1005] Processing: p60145.LC.21.99999.wav
[380/1005] Processing: p60145.LC.22.104.wav
[381/1005] Processing: p60145.LC.23.169.wav
[382/1005] Processing: p60145.LC.25.173.wav
[383/1005] Processing: p60145.LC.26.99999.wav
[384/1005] Processing: p60145.LC.28.175.wav
[385/1005] Processing: p60145.LC.32.53.wav
[386/1005] Processing: p60145.LC.33.40.wav
[387/1005] Processing: p60145.LC.34.30.wav
[388/1005] Processing: p60145.LC.35.92.wav
[389/1005] Processing: p60145.LC.36.99999.wav
[390/1005] Processing: p60145.LC.37.33.wav
[391/1005] Processing: p60145.LC.39.28.wav
[392/1005] Processing: p60145.LC.4.131.wav
[393/1005] Processing: p60145.LC.7.119.wav
[394/1005] Processing: p60145.LW.11.99999.wav
[395/1005] Processing: p60145.LW.17.113.wav
[396/1005] Processing: p60145.LW.27.18.wav
[397/1005] Processing: p60145.LW.31.99999.wav
[398/1005] Processing: p60145.LW.33.141.wav
[399/1005] Processing: p60145.LW.38.118.wav
[400/1005] Processing: p60145.LW.4.105.wav
[401/1005] Processing: p60145.LW.41.99999.wav
[402/1005] Processing: p60145.RC.11.99999.wav
[403/1005] Processing: p60145.RC.14.162.wav
[404/1005] Processing: p60145.RC.19.35.wav
[405/1005] Processing: p60145.RC.20.90.wav
[406/1005] Processing: p60145.RC.21.99999.wav
[407/1005] Processing: p60145.RC.22.97.wav
[408/1005] Processing: p60145.RC.23.123.wav
[409/1005] Processing: p60145.RC.24.113.wav
[410/1005] Processing: p60145.RC.25.61.wav
[411/1005] Processing: p60145.RC.26.99999.wav
[412/1005] Processing: p60145.RC.27.136.wav
[413/1005] Processing: p60145.RC.28.58.wav
[414/1005] Processing: p60145.RC.3.18.wav
[415/1005] Processing: p60145.RC.30.78.wav
[416/1005] Processing: p60145.RC.33.34.wav
[417/1005] Processing: p60145.RC.35.39.wav
[418/1005] Processing: p60145.RC.36.99999.wav
[419/1005] Processing: p60145.RC.8.3.wav
[420/1005] Processing: p60145.RC.9.8.wav
[421/1005] Processing: p60145.RW.12.145.wav
[422/1005] Processing: p60145.RW.17.186.wav
[423/1005] Processing: p60145.RW.24.5.wav
[424/1005] Processing: p60145.RW.34.100.wav
[425/1005] Processing: p60145.RW.41.99999.wav
[426/1005] Processing: p60145.RW.7.27.wav
[427/1005] Processing: p62650.LW.11.99999.wav
[428/1005] Processing: p62650.LW.16.99999.wav
[429/1005] Processing: p62650.LW.18.2.wav
[430/1005] Processing: p62650.LW.2.99.wav
[431/1005] Processing: p62650.LW.20.68.wav
[432/1005] Processing: p62650.LW.25.183.wav
[433/1005] Processing: p62650.LW.3.19.wav
[434/1005] Processing: p62650.RC.1.165.wav
[435/1005] Processing: p62650.RC.10.47.wav
[436/1005] Processing: p62650.RC.11.99999.wav
[437/1005] Processing: p62650.RC.12.26.wav
[438/1005] Processing: p62650.RC.14.6.wav
[439/1005] Processing: p62650.RC.16.99999.wav
[440/1005] Processing: p62650.RC.17.60.wav
[441/1005] Processing: p62650.RC.18.48.wav
[442/1005] Processing: p62650.RC.19.180.wav
[443/1005] Processing: p62650.RC.2.125.wav
[444/1005] Processing: p62650.RC.20.42.wav
[445/1005] Processing: p62650.RC.21.99999.wav
[446/1005] Processing: p62650.RC.23.101.wav
[447/1005] Processing: p62650.RC.24.51.wav
[448/1005] Processing: p62650.RC.25.46.wav
[449/1005] Processing: p62650.RC.26.99999.wav
[450/1005] Processing: p62650.RC.27.34.wav
[451/1005] Processing: p62650.RC.28.86.wav
[452/1005] Processing: p62650.RC.3.19.wav
[453/1005] Processing: p62650.RC.30.155.wav
[454/1005] Processing: p62650.RC.31.99999.wav
[455/1005] Processing: p62650.RC.4.138.wav
[456/1005] Processing: p62650.RC.5.16.wav
[457/1005] Processing: p62650.RC.6.99999.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,30.69632,0.263408,26.79142,33.90816,35.34396,...,-0.051319,-0.003878,0.117989,3.759399,3.065134,0.090000,0.043012,0.191111,0.162716,-33.63273
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,35.56685,0.143079,35.00103,35.37496,38.83751,...,-0.051151,0.000672,0.113700,3.773585,3.381643,0.081429,0.039795,0.194286,0.175650,-32.83780
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.37303,0.038734,33.31597,34.01617,35.35698,...,-0.055448,-0.000904,0.110642,3.083700,2.252252,0.136000,0.094149,0.238333,0.379448,-33.32463
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,29.84379,0.294935,14.94163,34.11031,36.57949,...,-0.043690,-0.003180,0.111289,4.464286,4.566210,0.085000,0.065000,0.125555,0.134504,-34.15696
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,32.33354,0.226291,32.81301,33.89858,37.18312,...,-0.053298,-0.000288,0.106116,2.966102,3.463203,0.087500,0.047368,0.178750,0.257849,-32.63171

OpenSMILE, intensity 6dB

In [22]:
# paths
BASE_DIR = Path(r"C:\Users\marti\Documents\Technical Medicine Master\Stages TM2\TM2-3\Technische opdracht")

OPENSMILE_EXE = BASE_DIR / "tools" / "openSMILE" / "bin" / "SMILExtract.exe"
CONFIG_FILE = BASE_DIR / "tools" / "openSMILE" / "config" / "egemaps" / "v02" / "eGeMAPSv02.conf"

AUDIO_ROOT = BASE_DIR / "TAME" / "wiener_intensity_perturbations_pain" / "+6dB"

OUTPUT_FEATURES_CSV = BASE_DIR / "opensmile_intensity_6dB_features_pain.csv"
OUTPUT_FAILED_CSV = BASE_DIR / "opensmile_intensity_6dB_failed_files.csv"

# check
print("SMILExtract exists:", OPENSMILE_EXE.exists())
print("Config exists:", CONFIG_FILE.exists())
print("Audio root exists:", AUDIO_ROOT.exists())

if not OPENSMILE_EXE.exists():
    raise FileNotFoundError(f"SMILExtract.exe not found:\n{OPENSMILE_EXE}")

if not CONFIG_FILE.exists():
    raise FileNotFoundError(f"Config file not found:\n{CONFIG_FILE}")

if not AUDIO_ROOT.exists():
    raise FileNotFoundError(f"Audio root not found:\n{AUDIO_ROOT}")

#WAV files
wav_files = sorted(AUDIO_ROOT.rglob("*.wav"))
print(f"Number of wav. files found: {len(wav_files)}")

if len(wav_files) == 0:
    raise ValueError("no .wav files found.")

# Run OpenSMILE
all_rows = []
failed_files = []

for i, wav_file in enumerate(wav_files, start=1):
    print(f"[{i}/{len(wav_files)}] Processing: {wav_file.name}")

    participant_id = wav_file.parent.name
    filename = wav_file.name

    with tempfile.NamedTemporaryFile(suffix=".csv", delete=False) as tmp:
        temp_output_csv = Path(tmp.name)

    try:
        if temp_output_csv.exists():
            temp_output_csv.unlink(missing_ok=True)

        cmd = [
            str(OPENSMILE_EXE),
            "-C", str(CONFIG_FILE),
            "-I", str(wav_file),
            "-csvoutput", str(temp_output_csv),
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode != 0:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "openSMILE return code != 0",
                "stderr": result.stderr
            })
            continue

        if not temp_output_csv.exists():
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "no output made",
                "stderr": result.stderr
            })
            continue

        try:
            feature_df = pd.read_csv(temp_output_csv, sep=";", engine="python")
        except Exception as e:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": f"error in csv: {e}",
                "stderr": result.stderr
            })
            continue

        if feature_df.empty:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "Output csv is leeg",
                "stderr": result.stderr
            })
            continue

        #adding information 
        row = feature_df.iloc[0].to_dict()
        row["name"] = filename
        row["participant_id"] = participant_id
        row["filename"] = filename
        row["file_path"] = str(wav_file)

        all_rows.append(row)

    except Exception as e:
        failed_files.append({
            "participant_id": participant_id,
            "filename": filename,
            "file_path": str(wav_file),
            "reason": f"error {e}",
            "stderr": ""
        })

    finally:
        if temp_output_csv.exists():
            temp_output_csv.unlink(missing_ok=True)


#Save
features_df = pd.DataFrame(all_rows)

# Kolommen netjes ordenen
preferred_front_cols = ["participant_id", "filename", "file_path", "name", "frameTime"]
remaining_cols = [col for col in features_df.columns if col not in preferred_front_cols]
features_df = features_df[[col for col in preferred_front_cols if col in features_df.columns] + remaining_cols]

features_df.to_csv(OUTPUT_FEATURES_CSV, index=False)

print("\nKlaar.")
print("number of errors in features:", len(features_df))
print("numer of errors in the files:", len(failed_files))
print("Features saves in :")
print(OUTPUT_FEATURES_CSV)

if failed_files:
    failed_df = pd.DataFrame(failed_files)
    failed_df.to_csv(OUTPUT_FAILED_CSV, index=False)
    print("\n errors saved:")
    print(OUTPUT_FAILED_CSV)


# Results
print("\nShape features dataframe:", features_df.shape)
display(features_df.head())

SMILExtract exists: True
Config exists: True
Audio root exists: True
Number of wav. files found: 1005
[1/1005] Processing: p10085.LC.1.161.wav
[2/1005] Processing: p10085.LC.12.59.wav
[3/1005] Processing: p10085.LC.14.45.wav
[4/1005] Processing: p10085.LC.18.41.wav
[5/1005] Processing: p10085.LC.2.106.wav
[6/1005] Processing: p10085.LC.23.156.wav
[7/1005] Processing: p10085.LC.24.172.wav
[8/1005] Processing: p10085.LC.26.99999.wav
[9/1005] Processing: p10085.LC.3.60.wav
[10/1005] Processing: p10085.LC.30.132.wav
[11/1005] Processing: p10085.LC.31.99999.wav
[12/1005] Processing: p10085.LC.33.6.wav
[13/1005] Processing: p10085.LC.34.122.wav
[14/1005] Processing: p10085.LC.37.71.wav
[15/1005] Processing: p10085.LC.38.160.wav
[16/1005] Processing: p10085.LC.4.76.wav
[17/1005] Processing: p10085.LC.40.174.wav
[18/1005] Processing: p10085.LC.41.99999.wav
[19/1005] Processing: p10085.LC.5.134.wav
[20/1005] Processing: p10085.LC.6.99999.wav
[21/1005] Processing: p10085.LC.9.55.wav
[22/1005] Processing: p10085.LW.28.85.wav
[23/1005] Processing: p10085.LW.36.99999.wav
[24/1005] Processing: p10085.RC.11.99999.wav
[25/1005] Processing: p10085.RC.12.165.wav
[26/1005] Processing: p10085.RC.13.36.wav
[27/1005] Processing: p10085.RC.14.86.wav
[28/1005] Processing: p10085.RC.16.99999.wav
[29/1005] Processing: p10085.RC.17.160.wav
[30/1005] Processing: p10085.RC.19.78.wav
[31/1005] Processing: p10085.RC.26.99999.wav
[32/1005] Processing: p10085.RC.28.52.wav
[33/1005] Processing: p10085.RC.29.182.wav
[34/1005] Processing: p10085.RC.3.58.wav
[35/1005] Processing: p10085.RC.30.53.wav
[36/1005] Processing: p10085.RC.31.99999.wav
[37/1005] Processing: p10085.RC.32.24.wav
[38/1005] Processing: p10085.RC.33.126.wav
[39/1005] Processing: p10085.RC.34.18.wav
[40/1005] Processing: p10085.RC.35.75.wav
[41/1005] Processing: p10085.RC.36.99999.wav
[42/1005] Processing: p10085.RC.8.50.wav
[43/1005] Processing: p10085.RC.9.85.wav
[44/1005] Processing: p15965.LC.10.146.wav
[45/1005] Processing: p15965.LC.11.99999.wav
[46/1005] Processing: p15965.LC.12.161.wav
[47/1005] Processing: p15965.LC.13.83.wav
[48/1005] Processing: p15965.LC.14.48.wav
[49/1005] Processing: p15965.LC.15.182.wav
[50/1005] Processing: p15965.LC.17.164.wav
[51/1005] Processing: p15965.LC.18.143.wav
[52/1005] Processing: p15965.LC.19.131.wav
[53/1005] Processing: p15965.LC.2.118.wav
[54/1005] Processing: p15965.LC.20.10.wav
[55/1005] Processing: p15965.LC.21.99999.wav
[56/1005] Processing: p15965.LC.23.178.wav
[57/1005] Processing: p15965.LC.24.36.wav
[58/1005] Processing: p15965.LC.26.99999.wav
[59/1005] Processing: p15965.LC.29.1.wav
[60/1005] Processing: p15965.LC.3.45.wav
[61/1005] Processing: p15965.LC.30.123.wav
[62/1005] Processing: p15965.LC.31.99999.wav
[63/1005] Processing: p15965.LC.32.30.wav
[64/1005] Processing: p15965.LC.33.46.wav
[65/1005] Processing: p15965.LC.34.147.wav
[66/1005] Processing: p15965.LC.35.155.wav
[67/1005] Processing: p15965.LC.36.99999.wav
[68/1005] Processing: p15965.LC.38.63.wav
[69/1005] Processing: p15965.LC.4.81.wav
[70/1005] Processing: p15965.LC.41.99999.wav
[71/1005] Processing: p15965.LC.5.163.wav
[72/1005] Processing: p15965.LC.6.99999.wav
[73/1005] Processing: p15965.LC.7.66.wav
[74/1005] Processing: p15965.LC.9.129.wav
[75/1005] Processing: p15965.LW.11.99999.wav
[76/1005] Processing: p15965.LW.12.45.wav
[77/1005] Processing: p15965.LW.13.41.wav
[78/1005] Processing: p15965.LW.16.99999.wav
[79/1005] Processing: p15965.LW.17.134.wav
[80/1005] Processing: p15965.LW.18.118.wav
[81/1005] Processing: p15965.LW.19.67.wav
[82/1005] Processing: p15965.LW.2.155.wav
[83/1005] Processing: p15965.LW.20.63.wav
[84/1005] Processing: p15965.LW.21.99999.wav
[85/1005] Processing: p15965.LW.23.29.wav
[86/1005] Processing: p15965.LW.24.83.wav
[87/1005] Processing: p15965.LW.25.102.wav
[88/1005] Processing: p15965.LW.26.99999.wav
[89/1005] Processing: p15965.LW.27.36.wav
[90/1005] Processing: p15965.LW.28.69.wav
[91/1005] Processing: p15965.LW.3.122.wav
[92/1005] Processing: p15965.LW.30.163.wav
[93/1005] Processing: p15965.LW.31.99999.wav
[94/1005] Processing: p15965.LW.32.137.wav
[95/1005] Processing: p15965.LW.33.4.wav
[96/1005] Processing: p15965.LW.34.170.wav
[97/1005] Processing: p15965.LW.35.43.wav
[98/1005] Processing: p15965.LW.36.99999.wav
[99/1005] Processing: p15965.LW.37.138.wav
[100/1005] Processing: p15965.LW.38.47.wav
[101/1005] Processing: p15965.LW.39.65.wav
[102/1005] Processing: p15965.LW.4.116.wav
[103/1005] Processing: p15965.LW.40.95.wav
[104/1005] Processing: p15965.LW.41.99999.wav
[105/1005] Processing: p15965.LW.5.172.wav
[106/1005] Processing: p15965.LW.6.99999.wav
[107/1005] Processing: p15965.LW.7.153.wav
[108/1005] Processing: p15965.LW.8.32.wav
[109/1005] Processing: p15965.LW.9.160.wav
[110/1005] Processing: p15965.RC.1.44.wav
[111/1005] Processing: p15965.RC.10.155.wav
[112/1005] Processing: p15965.RC.11.99999.wav
[113/1005] Processing: p15965.RC.12.28.wav
[114/1005] Processing: p15965.RC.13.105.wav
[115/1005] Processing: p15965.RC.14.185.wav
[116/1005] Processing: p15965.RC.15.125.wav
[117/1005] Processing: p15965.RC.16.99999.wav
[118/1005] Processing: p15965.RC.17.47.wav
[119/1005] Processing: p15965.RC.18.56.wav
[120/1005] Processing: p15965.RC.19.31.wav
[121/1005] Processing: p15965.RC.2.121.wav
[122/1005] Processing: p15965.RC.20.99.wav
[123/1005] Processing: p15965.RC.21.99999.wav
[124/1005] Processing: p15965.RC.22.158.wav
[125/1005] Processing: p15965.RC.23.37.wav
[126/1005] Processing: p15965.RC.24.2.wav
[127/1005] Processing: p15965.RC.25.154.wav
[128/1005] Processing: p15965.RC.27.18.wav
[129/1005] Processing: p15965.RC.29.120.wav
[130/1005] Processing: p15965.RC.30.42.wav
[131/1005] Processing: p15965.RC.31.99999.wav
[132/1005] Processing: p15965.RC.32.76.wav
[133/1005] Processing: p15965.RC.33.104.wav
[134/1005] Processing: p15965.RC.34.39.wav
[135/1005] Processing: p15965.RC.35.72.wav
[136/1005] Processing: p15965.RC.36.99999.wav
[137/1005] Processing: p15965.RC.37.68.wav
[138/1005] Processing: p15965.RC.38.137.wav
[139/1005] Processing: p15965.RC.39.24.wav
[140/1005] Processing: p15965.RC.4.136.wav
[141/1005] Processing: p15965.RC.41.99999.wav
[142/1005] Processing: p15965.RC.5.53.wav
[143/1005] Processing: p15965.RC.6.99999.wav
[144/1005] Processing: p15965.RC.7.135.wav
[145/1005] Processing: p15965.RC.8.117.wav
[146/1005] Processing: p15965.RW.1.39.wav
[147/1005] Processing: p15965.RW.10.2.wav
[148/1005] Processing: p15965.RW.11.99999.wav
[149/1005] Processing: p15965.RW.12.61.wav
[150/1005] Processing: p15965.RW.14.112.wav
[151/1005] Processing: p15965.RW.15.106.wav
[152/1005] Processing: p15965.RW.17.183.wav
[153/1005] Processing: p15965.RW.18.151.wav
[154/1005] Processing: p15965.RW.19.140.wav
[155/1005] Processing: p15965.RW.2.181.wav
[156/1005] Processing: p15965.RW.20.161.wav
[157/1005] Processing: p15965.RW.21.99999.wav
[158/1005] Processing: p15965.RW.22.168.wav
[159/1005] Processing: p15965.RW.23.153.wav
[160/1005] Processing: p15965.RW.24.44.wav
[161/1005] Processing: p15965.RW.25.159.wav
[162/1005] Processing: p15965.RW.27.117.wav
[163/1005] Processing: p15965.RW.28.0.wav
[164/1005] Processing: p15965.RW.29.156.wav
[165/1005] Processing: p15965.RW.3.115.wav
[166/1005] Processing: p15965.RW.30.178.wav
[167/1005] Processing: p15965.RW.32.149.wav
[168/1005] Processing: p15965.RW.33.30.wav
[169/1005] Processing: p15965.RW.34.167.wav
[170/1005] Processing: p15965.RW.35.74.wav
[171/1005] Processing: p15965.RW.36.99999.wav
[172/1005] Processing: p15965.RW.37.67.wav
[173/1005] Processing: p15965.RW.38.76.wav
[174/1005] Processing: p15965.RW.39.137.wav
[175/1005] Processing: p15965.RW.4.68.wav
[176/1005] Processing: p15965.RW.40.107.wav
[177/1005] Processing: p15965.RW.41.99999.wav
[178/1005] Processing: p15965.RW.5.42.wav
[179/1005] Processing: p15965.RW.8.65.wav
[180/1005] Processing: p15965.RW.9.49.wav
[181/1005] Processing: p18785.LC.1.123.wav
[182/1005] Processing: p18785.LC.13.38.wav
[183/1005] Processing: p18785.LC.14.143.wav
[184/1005] Processing: p18785.LC.4.100.wav
[185/1005] Processing: p18785.LC.6.99999.wav
[186/1005] Processing: p18785.LC.7.13.wav
[187/1005] Processing: p18785.LC.8.175.wav
[188/1005] Processing: p18785.LW.11.99999.wav
[189/1005] Processing: p18785.LW.19.97.wav
[190/1005] Processing: p18785.RC.1.31.wav
[191/1005] Processing: p18785.RC.12.77.wav
[192/1005] Processing: p18785.RC.13.18.wav
[193/1005] Processing: p18785.RC.15.96.wav
[194/1005] Processing: p18785.RC.2.187.wav
[195/1005] Processing: p18785.RC.3.103.wav
[196/1005] Processing: p18785.RC.4.63.wav
[197/1005] Processing: p18785.RC.5.24.wav
[198/1005] Processing: p18785.RW.12.58.wav
[199/1005] Processing: p18785.RW.15.165.wav
[200/1005] Processing: p18785.RW.16.99999.wav
[201/1005] Processing: p18785.RW.19.131.wav
[202/1005] Processing: p18785.RW.21.99999.wav
[203/1005] Processing: p18785.RW.26.99999.wav
[204/1005] Processing: p18785.RW.28.102.wav
[205/1005] Processing: p18785.RW.9.5.wav
[206/1005] Processing: p20960.LC.1.185.wav
[207/1005] Processing: p20960.LC.11.99999.wav
[208/1005] Processing: p20960.LC.12.92.wav
[209/1005] Processing: p20960.LC.13.43.wav
[210/1005] Processing: p20960.LC.14.18.wav
[211/1005] Processing: p20960.LC.15.141.wav
[212/1005] Processing: p20960.LC.19.6.wav
[213/1005] Processing: p20960.LC.2.84.wav
[214/1005] Processing: p20960.LC.20.120.wav
[215/1005] Processing: p20960.LC.23.37.wav
[216/1005] Processing: p20960.LC.24.25.wav
[217/1005] Processing: p20960.LC.27.140.wav
[218/1005] Processing: p20960.LC.28.83.wav
[219/1005] Processing: p20960.LC.29.182.wav
[220/1005] Processing: p20960.LC.3.40.wav
[221/1005] Processing: p20960.LC.30.128.wav
[222/1005] Processing: p20960.LC.31.99999.wav
[223/1005] Processing: p20960.LC.32.151.wav
[224/1005] Processing: p20960.LC.33.137.wav
[225/1005] Processing: p20960.LC.34.176.wav
[226/1005] Processing: p20960.LC.35.186.wav
[227/1005] Processing: p20960.LC.6.99999.wav
[228/1005] Processing: p20960.LC.7.1.wav
[229/1005] Processing: p20960.LW.19.31.wav
[230/1005] Processing: p20960.LW.5.165.wav
[231/1005] Processing: p20960.RC.13.88.wav
[232/1005] Processing: p20960.RC.16.99999.wav
[233/1005] Processing: p20960.RC.17.77.wav
[234/1005] Processing: p20960.RC.19.104.wav
[235/1005] Processing: p20960.RC.20.178.wav
[236/1005] Processing: p20960.RC.22.33.wav
[237/1005] Processing: p20960.RC.23.47.wav
[238/1005] Processing: p20960.RC.25.63.wav
[239/1005] Processing: p20960.RC.26.99999.wav
[240/1005] Processing: p20960.RC.27.56.wav
[241/1005] Processing: p20960.RC.28.58.wav
[242/1005] Processing: p20960.RC.30.143.wav
[243/1005] Processing: p20960.RC.31.99999.wav
[244/1005] Processing: p20960.RC.32.109.wav
[245/1005] Processing: p20960.RC.33.22.wav
[246/1005] Processing: p20960.RC.35.121.wav
[247/1005] Processing: p20960.RC.5.16.wav
[248/1005] Processing: p20960.RC.7.142.wav
[249/1005] Processing: p20960.RW.10.17.wav
[250/1005] Processing: p20960.RW.25.88.wav
[251/1005] Processing: p28030.LC.10.63.wav
[252/1005] Processing: p28030.LC.2.59.wav
[253/1005] Processing: p28030.LC.20.17.wav
[254/1005] Processing: p28030.LC.3.133.wav
[255/1005] Processing: p28030.LC.31.99999.wav
[256/1005] Processing: p28030.LC.5.23.wav
[257/1005] Processing: p28030.LC.7.86.wav
[258/1005] Processing: p28030.LC.8.188.wav
[259/1005] Processing: p28030.LC.9.12.wav
[260/1005] Processing: p28030.LW.15.107.wav
[261/1005] Processing: p28030.LW.16.99999.wav
[262/1005] Processing: p28030.LW.18.53.wav
[263/1005] Processing: p28030.LW.20.50.wav
[264/1005] Processing: p28030.RC.1.86.wav
[265/1005] Processing: p28030.RC.13.22.wav
[266/1005] Processing: p28030.RC.18.45.wav
[267/1005] Processing: p28030.RC.19.51.wav
[268/1005] Processing: p28030.RC.26.99999.wav
[269/1005] Processing: p28030.RC.29.39.wav
[270/1005] Processing: p28030.RC.3.7.wav
[271/1005] Processing: p28030.RC.30.118.wav
[272/1005] Processing: p28030.RC.33.152.wav
[273/1005] Processing: p28030.RC.36.99999.wav
[274/1005] Processing: p28030.RC.4.66.wav
[275/1005] Processing: p28030.RC.5.178.wav
[276/1005] Processing: p28030.RC.6.99999.wav
[277/1005] Processing: p28030.RW.13.175.wav
[278/1005] Processing: p28030.RW.16.99999.wav
[279/1005] Processing: p28030.RW.28.177.wav
[280/1005] Processing: p37540.LC.10.24.wav
[281/1005] Processing: p37540.LC.14.32.wav
[282/1005] Processing: p37540.LC.15.185.wav
[283/1005] Processing: p37540.LC.17.128.wav
[284/1005] Processing: p37540.LC.20.67.wav
[285/1005] Processing: p37540.LC.25.121.wav
[286/1005] Processing: p37540.LC.29.87.wav
[287/1005] Processing: p37540.LC.31.99999.wav
[288/1005] Processing: p37540.LC.33.166.wav
[289/1005] Processing: p37540.LC.34.30.wav
[290/1005] Processing: p37540.LC.35.48.wav
[291/1005] Processing: p37540.LC.36.99999.wav
[292/1005] Processing: p37540.LC.4.90.wav
[293/1005] Processing: p37540.LC.9.112.wav
[294/1005] Processing: p37540.LW.15.168.wav
[295/1005] Processing: p37540.LW.21.99999.wav
[296/1005] Processing: p37540.RC.11.99999.wav
[297/1005] Processing: p37540.RC.16.99999.wav
[298/1005] Processing: p37540.RC.17.131.wav
[299/1005] Processing: p37540.RC.18.186.wav
[300/1005] Processing: p37540.RC.21.99999.wav
[301/1005] Processing: p37540.RC.22.138.wav
[302/1005] Processing: p37540.RC.27.35.wav
[303/1005] Processing: p37540.RC.28.187.wav
[304/1005] Processing: p37540.RC.29.154.wav
[305/1005] Processing: p37540.RC.3.182.wav
[306/1005] Processing: p37540.RC.30.91.wav
[307/1005] Processing: p37540.RC.31.99999.wav
[308/1005] Processing: p37540.RC.32.119.wav
[309/1005] Processing: p37540.RC.33.93.wav
[310/1005] Processing: p37540.RC.36.99999.wav
[311/1005] Processing: p37540.RC.4.36.wav
[312/1005] Processing: p37540.RC.5.89.wav
[313/1005] Processing: p37540.RW.10.18.wav
[314/1005] Processing: p37540.RW.13.0.wav
[315/1005] Processing: p37540.RW.16.99999.wav
[316/1005] Processing: p37540.RW.25.135.wav
[317/1005] Processing: p37540.RW.36.99999.wav
[318/1005] Processing: p37540.RW.6.99999.wav
[319/1005] Processing: p37540.RW.9.30.wav
[320/1005] Processing: p59520.LC.1.148.wav
[321/1005] Processing: p59520.LC.10.66.wav
[322/1005] Processing: p59520.LC.12.181.wav
[323/1005] Processing: p59520.LC.13.107.wav
[324/1005] Processing: p59520.LC.14.153.wav
[325/1005] Processing: p59520.LC.15.47.wav
[326/1005] Processing: p59520.LC.16.99999.wav
[327/1005] Processing: p59520.LC.19.101.wav
[328/1005] Processing: p59520.LC.2.60.wav
[329/1005] Processing: p59520.LC.20.177.wav
[330/1005] Processing: p59520.LC.22.152.wav
[331/1005] Processing: p59520.LC.27.33.wav
[332/1005] Processing: p59520.LC.29.63.wav
[333/1005] Processing: p59520.LC.3.86.wav
[334/1005] Processing: p59520.LC.30.114.wav
[335/1005] Processing: p59520.LC.36.99999.wav
[336/1005] Processing: p59520.LC.4.137.wav
[337/1005] Processing: p59520.LC.5.140.wav
[338/1005] Processing: p59520.LC.6.99999.wav
[339/1005] Processing: p59520.LC.7.186.wav
[340/1005] Processing: p59520.LW.14.72.wav
[341/1005] Processing: p59520.LW.35.136.wav
[342/1005] Processing: p59520.LW.8.17.wav
[343/1005] Processing: p59520.RC.1.121.wav
[344/1005] Processing: p59520.RC.11.99999.wav
[345/1005] Processing: p59520.RC.12.8.wav
[346/1005] Processing: p59520.RC.14.162.wav
[347/1005] Processing: p59520.RC.2.156.wav
[348/1005] Processing: p59520.RC.21.99999.wav
[349/1005] Processing: p59520.RC.22.10.wav
[350/1005] Processing: p59520.RC.23.34.wav
[351/1005] Processing: p59520.RC.24.58.wav
[352/1005] Processing: p59520.RC.25.126.wav
[353/1005] Processing: p59520.RC.26.99999.wav
[354/1005] Processing: p59520.RC.28.57.wav
[355/1005] Processing: p59520.RC.29.184.wav
[356/1005] Processing: p59520.RC.3.13.wav
[357/1005] Processing: p59520.RC.32.30.wav
[358/1005] Processing: p59520.RC.33.71.wav
[359/1005] Processing: p59520.RC.34.174.wav
[360/1005] Processing: p59520.RC.35.76.wav
[361/1005] Processing: p59520.RC.36.99999.wav
[362/1005] Processing: p59520.RC.4.47.wav
[363/1005] Processing: p59520.RC.5.112.wav
[364/1005] Processing: p59520.RC.7.95.wav
[365/1005] Processing: p59520.RC.9.166.wav
[366/1005] Processing: p59520.RW.10.82.wav
[367/1005] Processing: p59520.RW.16.99999.wav
[368/1005] Processing: p59520.RW.17.74.wav
[369/1005] Processing: p59520.RW.24.130.wav
[370/1005] Processing: p59520.RW.25.79.wav
[371/1005] Processing: p59520.RW.3.66.wav
[372/1005] Processing: p59520.RW.34.156.wav
[373/1005] Processing: p60145.LC.11.99999.wav
[374/1005] Processing: p60145.LC.12.31.wav
[375/1005] Processing: p60145.LC.14.50.wav
[376/1005] Processing: p60145.LC.15.147.wav
[377/1005] Processing: p60145.LC.16.99999.wav
[378/1005] Processing: p60145.LC.17.32.wav
[379/1005] Processing: p60145.LC.21.99999.wav
[380/1005] Processing: p60145.LC.22.104.wav
[381/1005] Processing: p60145.LC.23.169.wav
[382/1005] Processing: p60145.LC.25.173.wav
[383/1005] Processing: p60145.LC.26.99999.wav
[384/1005] Processing: p60145.LC.28.175.wav
[385/1005] Processing: p60145.LC.32.53.wav
[386/1005] Processing: p60145.LC.33.40.wav
[387/1005] Processing: p60145.LC.34.30.wav
[388/1005] Processing: p60145.LC.35.92.wav
[389/1005] Processing: p60145.LC.36.99999.wav
[390/1005] Processing: p60145.LC.37.33.wav
[391/1005] Processing: p60145.LC.39.28.wav
[392/1005] Processing: p60145.LC.4.131.wav
[393/1005] Processing: p60145.LC.7.119.wav
[394/1005] Processing: p60145.LW.11.99999.wav
[395/1005] Processing: p60145.LW.17.113.wav
[396/1005] Processing: p60145.LW.27.18.wav
[397/1005] Processing: p60145.LW.31.99999.wav
[398/1005] Processing: p60145.LW.33.141.wav
[399/1005] Processing: p60145.LW.38.118.wav
[400/1005] Processing: p60145.LW.4.105.wav
[401/1005] Processing: p60145.LW.41.99999.wav
[402/1005] Processing: p60145.RC.11.99999.wav
[403/1005] Processing: p60145.RC.14.162.wav
[404/1005] Processing: p60145.RC.19.35.wav
[405/1005] Processing: p60145.RC.20.90.wav
[406/1005] Processing: p60145.RC.21.99999.wav
[407/1005] Processing: p60145.RC.22.97.wav
[408/1005] Processing: p60145.RC.23.123.wav
[409/1005] Processing: p60145.RC.24.113.wav
[410/1005] Processing: p60145.RC.25.61.wav
[411/1005] Processing: p60145.RC.26.99999.wav
[412/1005] Processing: p60145.RC.27.136.wav
[413/1005] Processing: p60145.RC.28.58.wav
[414/1005] Processing: p60145.RC.3.18.wav
[415/1005] Processing: p60145.RC.30.78.wav
[416/1005] Processing: p60145.RC.33.34.wav
[417/1005] Processing: p60145.RC.35.39.wav
[418/1005] Processing: p60145.RC.36.99999.wav
[419/1005] Processing: p60145.RC.8.3.wav
[420/1005] Processing: p60145.RC.9.8.wav
[421/1005] Processing: p60145.RW.12.145.wav
[422/1005] Processing: p60145.RW.17.186.wav
[423/1005] Processing: p60145.RW.24.5.wav
[424/1005] Processing: p60145.RW.34.100.wav
[425/1005] Processing: p60145.RW.41.99999.wav
[426/1005] Processing: p60145.RW.7.27.wav
[427/1005] Processing: p62650.LW.11.99999.wav
[428/1005] Processing: p62650.LW.16.99999.wav
[429/1005] Processing: p62650.LW.18.2.wav
[430/1005] Processing: p62650.LW.2.99.wav
[431/1005] Processing: p62650.LW.20.68.wav
[432/1005] Processing: p62650.LW.25.183.wav
[433/1005] Processing: p62650.LW.3.19.wav
[434/1005] Processing: p62650.RC.1.165.wav
[435/1005] Processing: p62650.RC.10.47.wav
[436/1005] Processing: p62650.RC.11.99999.wav
[437/1005] Processing: p62650.RC.12.26.wav
[438/1005] Processing: p62650.RC.14.6.wav
[439/1005] Processing: p62650.RC.16.99999.wav
[440/1005] Processing: p62650.RC.17.60.wav
[441/1005] Processing: p62650.RC.18.48.wav
[442/1005] Processing: p62650.RC.19.180.wav
[443/1005] Processing: p62650.RC.2.125.wav
[444/1005] Processing: p62650.RC.20.42.wav
[445/1005] Processing: p62650.RC.21.99999.wav
[446/1005] Processing: p62650.RC.23.101.wav
[447/1005] Processing: p62650.RC.24.51.wav
[448/1005] Processing: p62650.RC.25.46.wav
[449/1005] Processing: p62650.RC.26.99999.wav
[450/1005] Processing: p62650.RC.27.34.wav
[451/1005] Processing: p62650.RC.28.86.wav
[452/1005] Processing: p62650.RC.3.19.wav
[453/1005] Processing: p62650.RC.30.155.wav
[454/1005] Processing: p62650.RC.31.99999.wav
[455/1005] Processing: p62650.RC.4.138.wav
[456/1005] Processing: p62650.RC.5.16.wav
[457/1005] Processing: p62650.RC.6.99999.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,30.69635,0.263404,26.79143,33.90816,35.34415,...,-0.053734,-0.005464,0.166707,3.759399,3.065134,0.090000,0.043012,0.191111,0.162716,-30.63153
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,35.56689,0.143087,35.00103,35.37495,38.83751,...,-0.053561,-0.000992,0.160646,3.773585,3.381643,0.081429,0.039795,0.194286,0.175650,-29.83669
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.36367,0.038552,33.35046,34.00359,35.33626,...,-0.057934,-0.002568,0.156898,3.083700,2.252252,0.138000,0.091957,0.236667,0.375751,-30.32344
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,29.84393,0.294924,14.94218,34.11016,36.57948,...,-0.046096,-0.004819,0.157232,4.464286,4.566210,0.085000,0.065000,0.125555,0.134504,-31.15558
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,32.33355,0.226291,32.81295,33.89860,37.18318,...,-0.055687,-0.001900,0.149933,2.966102,3.463203,0.087500,0.047368,0.178750,0.257849,-29.63066

OpenSMILE, intensity -3dB

In [23]:
# paths
BASE_DIR = Path(r"C:\Users\marti\Documents\Technical Medicine Master\Stages TM2\TM2-3\Technische opdracht")

OPENSMILE_EXE = BASE_DIR / "tools" / "openSMILE" / "bin" / "SMILExtract.exe"
CONFIG_FILE = BASE_DIR / "tools" / "openSMILE" / "config" / "egemaps" / "v02" / "eGeMAPSv02.conf"

AUDIO_ROOT = BASE_DIR / "TAME" / "wiener_intensity_perturbations_pain" / "-3dB"

OUTPUT_FEATURES_CSV = BASE_DIR / "opensmile_intensity_-3dB_features_pain.csv"
OUTPUT_FAILED_CSV = BASE_DIR / "opensmile_intensity_-3dB_failed_files.csv"

# check
print("SMILExtract exists:", OPENSMILE_EXE.exists())
print("Config exists:", CONFIG_FILE.exists())
print("Audio root exists:", AUDIO_ROOT.exists())

if not OPENSMILE_EXE.exists():
    raise FileNotFoundError(f"SMILExtract.exe not found:\n{OPENSMILE_EXE}")

if not CONFIG_FILE.exists():
    raise FileNotFoundError(f"Config file not found:\n{CONFIG_FILE}")

if not AUDIO_ROOT.exists():
    raise FileNotFoundError(f"Audio root not found:\n{AUDIO_ROOT}")

#WAV files
wav_files = sorted(AUDIO_ROOT.rglob("*.wav"))
print(f"Number of wav. files found: {len(wav_files)}")

if len(wav_files) == 0:
    raise ValueError("no .wav files found.")

# Run OpenSMILE
all_rows = []
failed_files = []

for i, wav_file in enumerate(wav_files, start=1):
    print(f"[{i}/{len(wav_files)}] Processing: {wav_file.name}")

    participant_id = wav_file.parent.name
    filename = wav_file.name

    with tempfile.NamedTemporaryFile(suffix=".csv", delete=False) as tmp:
        temp_output_csv = Path(tmp.name)

    try:
        if temp_output_csv.exists():
            temp_output_csv.unlink(missing_ok=True)

        cmd = [
            str(OPENSMILE_EXE),
            "-C", str(CONFIG_FILE),
            "-I", str(wav_file),
            "-csvoutput", str(temp_output_csv),
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode != 0:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "openSMILE return code != 0",
                "stderr": result.stderr
            })
            continue

        if not temp_output_csv.exists():
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "no output made",
                "stderr": result.stderr
            })
            continue

        try:
            feature_df = pd.read_csv(temp_output_csv, sep=";", engine="python")
        except Exception as e:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": f"error in csv: {e}",
                "stderr": result.stderr
            })
            continue

        if feature_df.empty:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "Output csv is leeg",
                "stderr": result.stderr
            })
            continue

        #adding information 
        row = feature_df.iloc[0].to_dict()
        row["name"] = filename
        row["participant_id"] = participant_id
        row["filename"] = filename
        row["file_path"] = str(wav_file)

        all_rows.append(row)

    except Exception as e:
        failed_files.append({
            "participant_id": participant_id,
            "filename": filename,
            "file_path": str(wav_file),
            "reason": f"error {e}",
            "stderr": ""
        })

    finally:
        if temp_output_csv.exists():
            temp_output_csv.unlink(missing_ok=True)


#Save
features_df = pd.DataFrame(all_rows)

# Kolommen netjes ordenen
preferred_front_cols = ["participant_id", "filename", "file_path", "name", "frameTime"]
remaining_cols = [col for col in features_df.columns if col not in preferred_front_cols]
features_df = features_df[[col for col in preferred_front_cols if col in features_df.columns] + remaining_cols]

features_df.to_csv(OUTPUT_FEATURES_CSV, index=False)

print("\nKlaar.")
print("number of errors in features:", len(features_df))
print("numer of errors in the files:", len(failed_files))
print("Features saves in :")
print(OUTPUT_FEATURES_CSV)

if failed_files:
    failed_df = pd.DataFrame(failed_files)
    failed_df.to_csv(OUTPUT_FAILED_CSV, index=False)
    print("\n errors saved:")
    print(OUTPUT_FAILED_CSV)


# Results
print("\nShape features dataframe:", features_df.shape)
display(features_df.head())

SMILExtract exists: True
Config exists: True
Audio root exists: True
Number of wav. files found: 1005
[1/1005] Processing: p10085.LC.1.161.wav
[2/1005] Processing: p10085.LC.12.59.wav
[3/1005] Processing: p10085.LC.14.45.wav
[4/1005] Processing: p10085.LC.18.41.wav
[5/1005] Processing: p10085.LC.2.106.wav
[6/1005] Processing: p10085.LC.23.156.wav
[7/1005] Processing: p10085.LC.24.172.wav
[8/1005] Processing: p10085.LC.26.99999.wav
[9/1005] Processing: p10085.LC.3.60.wav
[10/1005] Processing: p10085.LC.30.132.wav
[11/1005] Processing: p10085.LC.31.99999.wav
[12/1005] Processing: p10085.LC.33.6.wav
[13/1005] Processing: p10085.LC.34.122.wav
[14/1005] Processing: p10085.LC.37.71.wav
[15/1005] Processing: p10085.LC.38.160.wav
[16/1005] Processing: p10085.LC.4.76.wav
[17/1005] Processing: p10085.LC.40.174.wav
[18/1005] Processing: p10085.LC.41.99999.wav
[19/1005] Processing: p10085.LC.5.134.wav
[20/1005] Processing: p10085.LC.6.99999.wav
[21/1005] Processing: p10085.LC.9.55.wav
[22/1005] Processing: p10085.LW.28.85.wav
[23/1005] Processing: p10085.LW.36.99999.wav
[24/1005] Processing: p10085.RC.11.99999.wav
[25/1005] Processing: p10085.RC.12.165.wav
[26/1005] Processing: p10085.RC.13.36.wav
[27/1005] Processing: p10085.RC.14.86.wav
[28/1005] Processing: p10085.RC.16.99999.wav
[29/1005] Processing: p10085.RC.17.160.wav
[30/1005] Processing: p10085.RC.19.78.wav
[31/1005] Processing: p10085.RC.26.99999.wav
[32/1005] Processing: p10085.RC.28.52.wav
[33/1005] Processing: p10085.RC.29.182.wav
[34/1005] Processing: p10085.RC.3.58.wav
[35/1005] Processing: p10085.RC.30.53.wav
[36/1005] Processing: p10085.RC.31.99999.wav
[37/1005] Processing: p10085.RC.32.24.wav
[38/1005] Processing: p10085.RC.33.126.wav
[39/1005] Processing: p10085.RC.34.18.wav
[40/1005] Processing: p10085.RC.35.75.wav
[41/1005] Processing: p10085.RC.36.99999.wav
[42/1005] Processing: p10085.RC.8.50.wav
[43/1005] Processing: p10085.RC.9.85.wav
[44/1005] Processing: p15965.LC.10.146.wav
[45/1005] Processing: p15965.LC.11.99999.wav
[46/1005] Processing: p15965.LC.12.161.wav
[47/1005] Processing: p15965.LC.13.83.wav
[48/1005] Processing: p15965.LC.14.48.wav
[49/1005] Processing: p15965.LC.15.182.wav
[50/1005] Processing: p15965.LC.17.164.wav
[51/1005] Processing: p15965.LC.18.143.wav
[52/1005] Processing: p15965.LC.19.131.wav
[53/1005] Processing: p15965.LC.2.118.wav
[54/1005] Processing: p15965.LC.20.10.wav
[55/1005] Processing: p15965.LC.21.99999.wav
[56/1005] Processing: p15965.LC.23.178.wav
[57/1005] Processing: p15965.LC.24.36.wav
[58/1005] Processing: p15965.LC.26.99999.wav
[59/1005] Processing: p15965.LC.29.1.wav
[60/1005] Processing: p15965.LC.3.45.wav
[61/1005] Processing: p15965.LC.30.123.wav
[62/1005] Processing: p15965.LC.31.99999.wav
[63/1005] Processing: p15965.LC.32.30.wav
[64/1005] Processing: p15965.LC.33.46.wav
[65/1005] Processing: p15965.LC.34.147.wav
[66/1005] Processing: p15965.LC.35.155.wav
[67/1005] Processing: p15965.LC.36.99999.wav
[68/1005] Processing: p15965.LC.38.63.wav
[69/1005] Processing: p15965.LC.4.81.wav
[70/1005] Processing: p15965.LC.41.99999.wav
[71/1005] Processing: p15965.LC.5.163.wav
[72/1005] Processing: p15965.LC.6.99999.wav
[73/1005] Processing: p15965.LC.7.66.wav
[74/1005] Processing: p15965.LC.9.129.wav
[75/1005] Processing: p15965.LW.11.99999.wav
[76/1005] Processing: p15965.LW.12.45.wav
[77/1005] Processing: p15965.LW.13.41.wav
[78/1005] Processing: p15965.LW.16.99999.wav
[79/1005] Processing: p15965.LW.17.134.wav
[80/1005] Processing: p15965.LW.18.118.wav
[81/1005] Processing: p15965.LW.19.67.wav
[82/1005] Processing: p15965.LW.2.155.wav
[83/1005] Processing: p15965.LW.20.63.wav
[84/1005] Processing: p15965.LW.21.99999.wav
[85/1005] Processing: p15965.LW.23.29.wav
[86/1005] Processing: p15965.LW.24.83.wav
[87/1005] Processing: p15965.LW.25.102.wav
[88/1005] Processing: p15965.LW.26.99999.wav
[89/1005] Processing: p15965.LW.27.36.wav
[90/1005] Processing: p15965.LW.28.69.wav
[91/1005] Processing: p15965.LW.3.122.wav
[92/1005] Processing: p15965.LW.30.163.wav
[93/1005] Processing: p15965.LW.31.99999.wav
[94/1005] Processing: p15965.LW.32.137.wav
[95/1005] Processing: p15965.LW.33.4.wav
[96/1005] Processing: p15965.LW.34.170.wav
[97/1005] Processing: p15965.LW.35.43.wav
[98/1005] Processing: p15965.LW.36.99999.wav
[99/1005] Processing: p15965.LW.37.138.wav
[100/1005] Processing: p15965.LW.38.47.wav
[101/1005] Processing: p15965.LW.39.65.wav
[102/1005] Processing: p15965.LW.4.116.wav
[103/1005] Processing: p15965.LW.40.95.wav
[104/1005] Processing: p15965.LW.41.99999.wav
[105/1005] Processing: p15965.LW.5.172.wav
[106/1005] Processing: p15965.LW.6.99999.wav
[107/1005] Processing: p15965.LW.7.153.wav
[108/1005] Processing: p15965.LW.8.32.wav
[109/1005] Processing: p15965.LW.9.160.wav
[110/1005] Processing: p15965.RC.1.44.wav
[111/1005] Processing: p15965.RC.10.155.wav
[112/1005] Processing: p15965.RC.11.99999.wav
[113/1005] Processing: p15965.RC.12.28.wav
[114/1005] Processing: p15965.RC.13.105.wav
[115/1005] Processing: p15965.RC.14.185.wav
[116/1005] Processing: p15965.RC.15.125.wav
[117/1005] Processing: p15965.RC.16.99999.wav
[118/1005] Processing: p15965.RC.17.47.wav
[119/1005] Processing: p15965.RC.18.56.wav
[120/1005] Processing: p15965.RC.19.31.wav
[121/1005] Processing: p15965.RC.2.121.wav
[122/1005] Processing: p15965.RC.20.99.wav
[123/1005] Processing: p15965.RC.21.99999.wav
[124/1005] Processing: p15965.RC.22.158.wav
[125/1005] Processing: p15965.RC.23.37.wav
[126/1005] Processing: p15965.RC.24.2.wav
[127/1005] Processing: p15965.RC.25.154.wav
[128/1005] Processing: p15965.RC.27.18.wav
[129/1005] Processing: p15965.RC.29.120.wav
[130/1005] Processing: p15965.RC.30.42.wav
[131/1005] Processing: p15965.RC.31.99999.wav
[132/1005] Processing: p15965.RC.32.76.wav
[133/1005] Processing: p15965.RC.33.104.wav
[134/1005] Processing: p15965.RC.34.39.wav
[135/1005] Processing: p15965.RC.35.72.wav
[136/1005] Processing: p15965.RC.36.99999.wav
[137/1005] Processing: p15965.RC.37.68.wav
[138/1005] Processing: p15965.RC.38.137.wav
[139/1005] Processing: p15965.RC.39.24.wav
[140/1005] Processing: p15965.RC.4.136.wav
[141/1005] Processing: p15965.RC.41.99999.wav
[142/1005] Processing: p15965.RC.5.53.wav
[143/1005] Processing: p15965.RC.6.99999.wav
[144/1005] Processing: p15965.RC.7.135.wav
[145/1005] Processing: p15965.RC.8.117.wav
[146/1005] Processing: p15965.RW.1.39.wav
[147/1005] Processing: p15965.RW.10.2.wav
[148/1005] Processing: p15965.RW.11.99999.wav
[149/1005] Processing: p15965.RW.12.61.wav
[150/1005] Processing: p15965.RW.14.112.wav
[151/1005] Processing: p15965.RW.15.106.wav
[152/1005] Processing: p15965.RW.17.183.wav
[153/1005] Processing: p15965.RW.18.151.wav
[154/1005] Processing: p15965.RW.19.140.wav
[155/1005] Processing: p15965.RW.2.181.wav
[156/1005] Processing: p15965.RW.20.161.wav
[157/1005] Processing: p15965.RW.21.99999.wav
[158/1005] Processing: p15965.RW.22.168.wav
[159/1005] Processing: p15965.RW.23.153.wav
[160/1005] Processing: p15965.RW.24.44.wav
[161/1005] Processing: p15965.RW.25.159.wav
[162/1005] Processing: p15965.RW.27.117.wav
[163/1005] Processing: p15965.RW.28.0.wav
[164/1005] Processing: p15965.RW.29.156.wav
[165/1005] Processing: p15965.RW.3.115.wav
[166/1005] Processing: p15965.RW.30.178.wav
[167/1005] Processing: p15965.RW.32.149.wav
[168/1005] Processing: p15965.RW.33.30.wav
[169/1005] Processing: p15965.RW.34.167.wav
[170/1005] Processing: p15965.RW.35.74.wav
[171/1005] Processing: p15965.RW.36.99999.wav
[172/1005] Processing: p15965.RW.37.67.wav
[173/1005] Processing: p15965.RW.38.76.wav
[174/1005] Processing: p15965.RW.39.137.wav
[175/1005] Processing: p15965.RW.4.68.wav
[176/1005] Processing: p15965.RW.40.107.wav
[177/1005] Processing: p15965.RW.41.99999.wav
[178/1005] Processing: p15965.RW.5.42.wav
[179/1005] Processing: p15965.RW.8.65.wav
[180/1005] Processing: p15965.RW.9.49.wav
[181/1005] Processing: p18785.LC.1.123.wav
[182/1005] Processing: p18785.LC.13.38.wav
[183/1005] Processing: p18785.LC.14.143.wav
[184/1005] Processing: p18785.LC.4.100.wav
[185/1005] Processing: p18785.LC.6.99999.wav
[186/1005] Processing: p18785.LC.7.13.wav
[187/1005] Processing: p18785.LC.8.175.wav
[188/1005] Processing: p18785.LW.11.99999.wav
[189/1005] Processing: p18785.LW.19.97.wav
[190/1005] Processing: p18785.RC.1.31.wav
[191/1005] Processing: p18785.RC.12.77.wav
[192/1005] Processing: p18785.RC.13.18.wav
[193/1005] Processing: p18785.RC.15.96.wav
[194/1005] Processing: p18785.RC.2.187.wav
[195/1005] Processing: p18785.RC.3.103.wav
[196/1005] Processing: p18785.RC.4.63.wav
[197/1005] Processing: p18785.RC.5.24.wav
[198/1005] Processing: p18785.RW.12.58.wav
[199/1005] Processing: p18785.RW.15.165.wav
[200/1005] Processing: p18785.RW.16.99999.wav
[201/1005] Processing: p18785.RW.19.131.wav
[202/1005] Processing: p18785.RW.21.99999.wav
[203/1005] Processing: p18785.RW.26.99999.wav
[204/1005] Processing: p18785.RW.28.102.wav
[205/1005] Processing: p18785.RW.9.5.wav
[206/1005] Processing: p20960.LC.1.185.wav
[207/1005] Processing: p20960.LC.11.99999.wav
[208/1005] Processing: p20960.LC.12.92.wav
[209/1005] Processing: p20960.LC.13.43.wav
[210/1005] Processing: p20960.LC.14.18.wav
[211/1005] Processing: p20960.LC.15.141.wav
[212/1005] Processing: p20960.LC.19.6.wav
[213/1005] Processing: p20960.LC.2.84.wav
[214/1005] Processing: p20960.LC.20.120.wav
[215/1005] Processing: p20960.LC.23.37.wav
[216/1005] Processing: p20960.LC.24.25.wav
[217/1005] Processing: p20960.LC.27.140.wav
[218/1005] Processing: p20960.LC.28.83.wav
[219/1005] Processing: p20960.LC.29.182.wav
[220/1005] Processing: p20960.LC.3.40.wav
[221/1005] Processing: p20960.LC.30.128.wav
[222/1005] Processing: p20960.LC.31.99999.wav
[223/1005] Processing: p20960.LC.32.151.wav
[224/1005] Processing: p20960.LC.33.137.wav
[225/1005] Processing: p20960.LC.34.176.wav
[226/1005] Processing: p20960.LC.35.186.wav
[227/1005] Processing: p20960.LC.6.99999.wav
[228/1005] Processing: p20960.LC.7.1.wav
[229/1005] Processing: p20960.LW.19.31.wav
[230/1005] Processing: p20960.LW.5.165.wav
[231/1005] Processing: p20960.RC.13.88.wav
[232/1005] Processing: p20960.RC.16.99999.wav
[233/1005] Processing: p20960.RC.17.77.wav
[234/1005] Processing: p20960.RC.19.104.wav
[235/1005] Processing: p20960.RC.20.178.wav
[236/1005] Processing: p20960.RC.22.33.wav
[237/1005] Processing: p20960.RC.23.47.wav
[238/1005] Processing: p20960.RC.25.63.wav
[239/1005] Processing: p20960.RC.26.99999.wav
[240/1005] Processing: p20960.RC.27.56.wav
[241/1005] Processing: p20960.RC.28.58.wav
[242/1005] Processing: p20960.RC.30.143.wav
[243/1005] Processing: p20960.RC.31.99999.wav
[244/1005] Processing: p20960.RC.32.109.wav
[245/1005] Processing: p20960.RC.33.22.wav
[246/1005] Processing: p20960.RC.35.121.wav
[247/1005] Processing: p20960.RC.5.16.wav
[248/1005] Processing: p20960.RC.7.142.wav
[249/1005] Processing: p20960.RW.10.17.wav
[250/1005] Processing: p20960.RW.25.88.wav
[251/1005] Processing: p28030.LC.10.63.wav
[252/1005] Processing: p28030.LC.2.59.wav
[253/1005] Processing: p28030.LC.20.17.wav
[254/1005] Processing: p28030.LC.3.133.wav
[255/1005] Processing: p28030.LC.31.99999.wav
[256/1005] Processing: p28030.LC.5.23.wav
[257/1005] Processing: p28030.LC.7.86.wav
[258/1005] Processing: p28030.LC.8.188.wav
[259/1005] Processing: p28030.LC.9.12.wav
[260/1005] Processing: p28030.LW.15.107.wav
[261/1005] Processing: p28030.LW.16.99999.wav
[262/1005] Processing: p28030.LW.18.53.wav
[263/1005] Processing: p28030.LW.20.50.wav
[264/1005] Processing: p28030.RC.1.86.wav
[265/1005] Processing: p28030.RC.13.22.wav
[266/1005] Processing: p28030.RC.18.45.wav
[267/1005] Processing: p28030.RC.19.51.wav
[268/1005] Processing: p28030.RC.26.99999.wav
[269/1005] Processing: p28030.RC.29.39.wav
[270/1005] Processing: p28030.RC.3.7.wav
[271/1005] Processing: p28030.RC.30.118.wav
[272/1005] Processing: p28030.RC.33.152.wav
[273/1005] Processing: p28030.RC.36.99999.wav
[274/1005] Processing: p28030.RC.4.66.wav
[275/1005] Processing: p28030.RC.5.178.wav
[276/1005] Processing: p28030.RC.6.99999.wav
[277/1005] Processing: p28030.RW.13.175.wav
[278/1005] Processing: p28030.RW.16.99999.wav
[279/1005] Processing: p28030.RW.28.177.wav
[280/1005] Processing: p37540.LC.10.24.wav
[281/1005] Processing: p37540.LC.14.32.wav
[282/1005] Processing: p37540.LC.15.185.wav
[283/1005] Processing: p37540.LC.17.128.wav
[284/1005] Processing: p37540.LC.20.67.wav
[285/1005] Processing: p37540.LC.25.121.wav
[286/1005] Processing: p37540.LC.29.87.wav
[287/1005] Processing: p37540.LC.31.99999.wav
[288/1005] Processing: p37540.LC.33.166.wav
[289/1005] Processing: p37540.LC.34.30.wav
[290/1005] Processing: p37540.LC.35.48.wav
[291/1005] Processing: p37540.LC.36.99999.wav
[292/1005] Processing: p37540.LC.4.90.wav
[293/1005] Processing: p37540.LC.9.112.wav
[294/1005] Processing: p37540.LW.15.168.wav
[295/1005] Processing: p37540.LW.21.99999.wav
[296/1005] Processing: p37540.RC.11.99999.wav
[297/1005] Processing: p37540.RC.16.99999.wav
[298/1005] Processing: p37540.RC.17.131.wav
[299/1005] Processing: p37540.RC.18.186.wav
[300/1005] Processing: p37540.RC.21.99999.wav
[301/1005] Processing: p37540.RC.22.138.wav
[302/1005] Processing: p37540.RC.27.35.wav
[303/1005] Processing: p37540.RC.28.187.wav
[304/1005] Processing: p37540.RC.29.154.wav
[305/1005] Processing: p37540.RC.3.182.wav
[306/1005] Processing: p37540.RC.30.91.wav
[307/1005] Processing: p37540.RC.31.99999.wav
[308/1005] Processing: p37540.RC.32.119.wav
[309/1005] Processing: p37540.RC.33.93.wav
[310/1005] Processing: p37540.RC.36.99999.wav
[311/1005] Processing: p37540.RC.4.36.wav
[312/1005] Processing: p37540.RC.5.89.wav
[313/1005] Processing: p37540.RW.10.18.wav
[314/1005] Processing: p37540.RW.13.0.wav
[315/1005] Processing: p37540.RW.16.99999.wav
[316/1005] Processing: p37540.RW.25.135.wav
[317/1005] Processing: p37540.RW.36.99999.wav
[318/1005] Processing: p37540.RW.6.99999.wav
[319/1005] Processing: p37540.RW.9.30.wav
[320/1005] Processing: p59520.LC.1.148.wav
[321/1005] Processing: p59520.LC.10.66.wav
[322/1005] Processing: p59520.LC.12.181.wav
[323/1005] Processing: p59520.LC.13.107.wav
[324/1005] Processing: p59520.LC.14.153.wav
[325/1005] Processing: p59520.LC.15.47.wav
[326/1005] Processing: p59520.LC.16.99999.wav
[327/1005] Processing: p59520.LC.19.101.wav
[328/1005] Processing: p59520.LC.2.60.wav
[329/1005] Processing: p59520.LC.20.177.wav
[330/1005] Processing: p59520.LC.22.152.wav
[331/1005] Processing: p59520.LC.27.33.wav
[332/1005] Processing: p59520.LC.29.63.wav
[333/1005] Processing: p59520.LC.3.86.wav
[334/1005] Processing: p59520.LC.30.114.wav
[335/1005] Processing: p59520.LC.36.99999.wav
[336/1005] Processing: p59520.LC.4.137.wav
[337/1005] Processing: p59520.LC.5.140.wav
[338/1005] Processing: p59520.LC.6.99999.wav
[339/1005] Processing: p59520.LC.7.186.wav
[340/1005] Processing: p59520.LW.14.72.wav
[341/1005] Processing: p59520.LW.35.136.wav
[342/1005] Processing: p59520.LW.8.17.wav
[343/1005] Processing: p59520.RC.1.121.wav
[344/1005] Processing: p59520.RC.11.99999.wav
[345/1005] Processing: p59520.RC.12.8.wav
[346/1005] Processing: p59520.RC.14.162.wav
[347/1005] Processing: p59520.RC.2.156.wav
[348/1005] Processing: p59520.RC.21.99999.wav
[349/1005] Processing: p59520.RC.22.10.wav
[350/1005] Processing: p59520.RC.23.34.wav
[351/1005] Processing: p59520.RC.24.58.wav
[352/1005] Processing: p59520.RC.25.126.wav
[353/1005] Processing: p59520.RC.26.99999.wav
[354/1005] Processing: p59520.RC.28.57.wav
[355/1005] Processing: p59520.RC.29.184.wav
[356/1005] Processing: p59520.RC.3.13.wav
[357/1005] Processing: p59520.RC.32.30.wav
[358/1005] Processing: p59520.RC.33.71.wav
[359/1005] Processing: p59520.RC.34.174.wav
[360/1005] Processing: p59520.RC.35.76.wav
[361/1005] Processing: p59520.RC.36.99999.wav
[362/1005] Processing: p59520.RC.4.47.wav
[363/1005] Processing: p59520.RC.5.112.wav
[364/1005] Processing: p59520.RC.7.95.wav
[365/1005] Processing: p59520.RC.9.166.wav
[366/1005] Processing: p59520.RW.10.82.wav
[367/1005] Processing: p59520.RW.16.99999.wav
[368/1005] Processing: p59520.RW.17.74.wav
[369/1005] Processing: p59520.RW.24.130.wav
[370/1005] Processing: p59520.RW.25.79.wav
[371/1005] Processing: p59520.RW.3.66.wav
[372/1005] Processing: p59520.RW.34.156.wav
[373/1005] Processing: p60145.LC.11.99999.wav
[374/1005] Processing: p60145.LC.12.31.wav
[375/1005] Processing: p60145.LC.14.50.wav
[376/1005] Processing: p60145.LC.15.147.wav
[377/1005] Processing: p60145.LC.16.99999.wav
[378/1005] Processing: p60145.LC.17.32.wav
[379/1005] Processing: p60145.LC.21.99999.wav
[380/1005] Processing: p60145.LC.22.104.wav
[381/1005] Processing: p60145.LC.23.169.wav
[382/1005] Processing: p60145.LC.25.173.wav
[383/1005] Processing: p60145.LC.26.99999.wav
[384/1005] Processing: p60145.LC.28.175.wav
[385/1005] Processing: p60145.LC.32.53.wav
[386/1005] Processing: p60145.LC.33.40.wav
[387/1005] Processing: p60145.LC.34.30.wav
[388/1005] Processing: p60145.LC.35.92.wav
[389/1005] Processing: p60145.LC.36.99999.wav
[390/1005] Processing: p60145.LC.37.33.wav
[391/1005] Processing: p60145.LC.39.28.wav
[392/1005] Processing: p60145.LC.4.131.wav
[393/1005] Processing: p60145.LC.7.119.wav
[394/1005] Processing: p60145.LW.11.99999.wav
[395/1005] Processing: p60145.LW.17.113.wav
[396/1005] Processing: p60145.LW.27.18.wav
[397/1005] Processing: p60145.LW.31.99999.wav
[398/1005] Processing: p60145.LW.33.141.wav
[399/1005] Processing: p60145.LW.38.118.wav
[400/1005] Processing: p60145.LW.4.105.wav
[401/1005] Processing: p60145.LW.41.99999.wav
[402/1005] Processing: p60145.RC.11.99999.wav
[403/1005] Processing: p60145.RC.14.162.wav
[404/1005] Processing: p60145.RC.19.35.wav
[405/1005] Processing: p60145.RC.20.90.wav
[406/1005] Processing: p60145.RC.21.99999.wav
[407/1005] Processing: p60145.RC.22.97.wav
[408/1005] Processing: p60145.RC.23.123.wav
[409/1005] Processing: p60145.RC.24.113.wav
[410/1005] Processing: p60145.RC.25.61.wav
[411/1005] Processing: p60145.RC.26.99999.wav
[412/1005] Processing: p60145.RC.27.136.wav
[413/1005] Processing: p60145.RC.28.58.wav
[414/1005] Processing: p60145.RC.3.18.wav
[415/1005] Processing: p60145.RC.30.78.wav
[416/1005] Processing: p60145.RC.33.34.wav
[417/1005] Processing: p60145.RC.35.39.wav
[418/1005] Processing: p60145.RC.36.99999.wav
[419/1005] Processing: p60145.RC.8.3.wav
[420/1005] Processing: p60145.RC.9.8.wav
[421/1005] Processing: p60145.RW.12.145.wav
[422/1005] Processing: p60145.RW.17.186.wav
[423/1005] Processing: p60145.RW.24.5.wav
[424/1005] Processing: p60145.RW.34.100.wav
[425/1005] Processing: p60145.RW.41.99999.wav
[426/1005] Processing: p60145.RW.7.27.wav
[427/1005] Processing: p62650.LW.11.99999.wav
[428/1005] Processing: p62650.LW.16.99999.wav
[429/1005] Processing: p62650.LW.18.2.wav
[430/1005] Processing: p62650.LW.2.99.wav
[431/1005] Processing: p62650.LW.20.68.wav
[432/1005] Processing: p62650.LW.25.183.wav
[433/1005] Processing: p62650.LW.3.19.wav
[434/1005] Processing: p62650.RC.1.165.wav
[435/1005] Processing: p62650.RC.10.47.wav
[436/1005] Processing: p62650.RC.11.99999.wav
[437/1005] Processing: p62650.RC.12.26.wav
[438/1005] Processing: p62650.RC.14.6.wav
[439/1005] Processing: p62650.RC.16.99999.wav
[440/1005] Processing: p62650.RC.17.60.wav
[441/1005] Processing: p62650.RC.18.48.wav
[442/1005] Processing: p62650.RC.19.180.wav
[443/1005] Processing: p62650.RC.2.125.wav
[444/1005] Processing: p62650.RC.20.42.wav
[445/1005] Processing: p62650.RC.21.99999.wav
[446/1005] Processing: p62650.RC.23.101.wav
[447/1005] Processing: p62650.RC.24.51.wav
[448/1005] Processing: p62650.RC.25.46.wav
[449/1005] Processing: p62650.RC.26.99999.wav
[450/1005] Processing: p62650.RC.27.34.wav
[451/1005] Processing: p62650.RC.28.86.wav
[452/1005] Processing: p62650.RC.3.19.wav
[453/1005] Processing: p62650.RC.30.155.wav
[454/1005] Processing: p62650.RC.31.99999.wav
[455/1005] Processing: p62650.RC.4.138.wav
[456/1005] Processing: p62650.RC.5.16.wav
[457/1005] Processing: p62650.RC.6.99999.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,30.69629,0.263410,26.79101,33.90815,35.34415,...,-0.046522,-0.000581,0.059085,3.759399,3.065134,0.090000,0.043012,0.191111,0.162716,-39.63684
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,35.56824,0.142929,35.00096,35.37488,38.83756,...,-0.046318,0.003799,0.056944,3.773585,3.381643,0.081429,0.039795,0.194286,0.175650,-38.84159
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.36366,0.038550,33.35046,34.00276,35.33625,...,-0.050708,0.002426,0.055607,3.083700,2.252252,0.138000,0.091957,0.236667,0.375751,-39.32865
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,29.84385,0.294931,14.93992,34.11039,36.57951,...,-0.038864,0.000148,0.055731,4.464286,4.566210,0.085000,0.065000,0.125555,0.134504,-40.16165
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,32.33356,0.226291,32.81295,33.89858,37.18306,...,-0.048493,0.003067,0.053136,2.966102,3.463203,0.087500,0.047368,0.178750,0.257849,-38.63521

OpenSMILE, intensity -6dB

In [24]:
# paths
BASE_DIR = Path(r"C:\Users\marti\Documents\Technical Medicine Master\Stages TM2\TM2-3\Technische opdracht")

OPENSMILE_EXE = BASE_DIR / "tools" / "openSMILE" / "bin" / "SMILExtract.exe"
CONFIG_FILE = BASE_DIR / "tools" / "openSMILE" / "config" / "egemaps" / "v02" / "eGeMAPSv02.conf"

AUDIO_ROOT = BASE_DIR / "TAME" / "wiener_intensity_perturbations_pain" / "-6dB"

OUTPUT_FEATURES_CSV = BASE_DIR / "opensmile_intensity_-6dB_features_pain.csv"
OUTPUT_FAILED_CSV = BASE_DIR / "opensmile_intensity_-6dB_failed_files.csv"

# check
print("SMILExtract exists:", OPENSMILE_EXE.exists())
print("Config exists:", CONFIG_FILE.exists())
print("Audio root exists:", AUDIO_ROOT.exists())

if not OPENSMILE_EXE.exists():
    raise FileNotFoundError(f"SMILExtract.exe not found:\n{OPENSMILE_EXE}")

if not CONFIG_FILE.exists():
    raise FileNotFoundError(f"Config file not found:\n{CONFIG_FILE}")

if not AUDIO_ROOT.exists():
    raise FileNotFoundError(f"Audio root not found:\n{AUDIO_ROOT}")

#WAV files
wav_files = sorted(AUDIO_ROOT.rglob("*.wav"))
print(f"Number of wav. files found: {len(wav_files)}")

if len(wav_files) == 0:
    raise ValueError("no .wav files found.")

# Run OpenSMILE
all_rows = []
failed_files = []

for i, wav_file in enumerate(wav_files, start=1):
    print(f"[{i}/{len(wav_files)}] Processing: {wav_file.name}")

    participant_id = wav_file.parent.name
    filename = wav_file.name

    with tempfile.NamedTemporaryFile(suffix=".csv", delete=False) as tmp:
        temp_output_csv = Path(tmp.name)

    try:
        if temp_output_csv.exists():
            temp_output_csv.unlink(missing_ok=True)

        cmd = [
            str(OPENSMILE_EXE),
            "-C", str(CONFIG_FILE),
            "-I", str(wav_file),
            "-csvoutput", str(temp_output_csv),
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode != 0:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "openSMILE return code != 0",
                "stderr": result.stderr
            })
            continue

        if not temp_output_csv.exists():
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "no output made",
                "stderr": result.stderr
            })
            continue

        try:
            feature_df = pd.read_csv(temp_output_csv, sep=";", engine="python")
        except Exception as e:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": f"error in csv: {e}",
                "stderr": result.stderr
            })
            continue

        if feature_df.empty:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": "Output csv is leeg",
                "stderr": result.stderr
            })
            continue

        #adding information 
        row = feature_df.iloc[0].to_dict()
        row["name"] = filename
        row["participant_id"] = participant_id
        row["filename"] = filename
        row["file_path"] = str(wav_file)

        all_rows.append(row)

    except Exception as e:
        failed_files.append({
            "participant_id": participant_id,
            "filename": filename,
            "file_path": str(wav_file),
            "reason": f"error {e}",
            "stderr": ""
        })

    finally:
        if temp_output_csv.exists():
            temp_output_csv.unlink(missing_ok=True)


#Save
features_df = pd.DataFrame(all_rows)

# Kolommen netjes ordenen
preferred_front_cols = ["participant_id", "filename", "file_path", "name", "frameTime"]
remaining_cols = [col for col in features_df.columns if col not in preferred_front_cols]
features_df = features_df[[col for col in preferred_front_cols if col in features_df.columns] + remaining_cols]

features_df.to_csv(OUTPUT_FEATURES_CSV, index=False)

print("\nKlaar.")
print("number of errors in features:", len(features_df))
print("numer of errors in the files:", len(failed_files))
print("Features saves in :")
print(OUTPUT_FEATURES_CSV)

if failed_files:
    failed_df = pd.DataFrame(failed_files)
    failed_df.to_csv(OUTPUT_FAILED_CSV, index=False)
    print("\n errors saved:")
    print(OUTPUT_FAILED_CSV)


# Results
print("\nShape features dataframe:", features_df.shape)
display(features_df.head())

SMILExtract exists: True
Config exists: True
Audio root exists: True
Number of wav. files found: 1005
[1/1005] Processing: p10085.LC.1.161.wav
[2/1005] Processing: p10085.LC.12.59.wav
[3/1005] Processing: p10085.LC.14.45.wav
[4/1005] Processing: p10085.LC.18.41.wav
[5/1005] Processing: p10085.LC.2.106.wav
[6/1005] Processing: p10085.LC.23.156.wav
[7/1005] Processing: p10085.LC.24.172.wav
[8/1005] Processing: p10085.LC.26.99999.wav
[9/1005] Processing: p10085.LC.3.60.wav
[10/1005] Processing: p10085.LC.30.132.wav
[11/1005] Processing: p10085.LC.31.99999.wav
[12/1005] Processing: p10085.LC.33.6.wav
[13/1005] Processing: p10085.LC.34.122.wav
[14/1005] Processing: p10085.LC.37.71.wav
[15/1005] Processing: p10085.LC.38.160.wav
[16/1005] Processing: p10085.LC.4.76.wav
[17/1005] Processing: p10085.LC.40.174.wav
[18/1005] Processing: p10085.LC.41.99999.wav
[19/1005] Processing: p10085.LC.5.134.wav
[20/1005] Processing: p10085.LC.6.99999.wav
[21/1005] Processing: p10085.LC.9.55.wav
[22/1005] Processing: p10085.LW.28.85.wav
[23/1005] Processing: p10085.LW.36.99999.wav
[24/1005] Processing: p10085.RC.11.99999.wav
[25/1005] Processing: p10085.RC.12.165.wav
[26/1005] Processing: p10085.RC.13.36.wav
[27/1005] Processing: p10085.RC.14.86.wav
[28/1005] Processing: p10085.RC.16.99999.wav
[29/1005] Processing: p10085.RC.17.160.wav
[30/1005] Processing: p10085.RC.19.78.wav
[31/1005] Processing: p10085.RC.26.99999.wav
[32/1005] Processing: p10085.RC.28.52.wav
[33/1005] Processing: p10085.RC.29.182.wav
[34/1005] Processing: p10085.RC.3.58.wav
[35/1005] Processing: p10085.RC.30.53.wav
[36/1005] Processing: p10085.RC.31.99999.wav
[37/1005] Processing: p10085.RC.32.24.wav
[38/1005] Processing: p10085.RC.33.126.wav
[39/1005] Processing: p10085.RC.34.18.wav
[40/1005] Processing: p10085.RC.35.75.wav
[41/1005] Processing: p10085.RC.36.99999.wav
[42/1005] Processing: p10085.RC.8.50.wav
[43/1005] Processing: p10085.RC.9.85.wav
[44/1005] Processing: p15965.LC.10.146.wav
[45/1005] Processing: p15965.LC.11.99999.wav
[46/1005] Processing: p15965.LC.12.161.wav
[47/1005] Processing: p15965.LC.13.83.wav
[48/1005] Processing: p15965.LC.14.48.wav
[49/1005] Processing: p15965.LC.15.182.wav
[50/1005] Processing: p15965.LC.17.164.wav
[51/1005] Processing: p15965.LC.18.143.wav
[52/1005] Processing: p15965.LC.19.131.wav
[53/1005] Processing: p15965.LC.2.118.wav
[54/1005] Processing: p15965.LC.20.10.wav
[55/1005] Processing: p15965.LC.21.99999.wav
[56/1005] Processing: p15965.LC.23.178.wav
[57/1005] Processing: p15965.LC.24.36.wav
[58/1005] Processing: p15965.LC.26.99999.wav
[59/1005] Processing: p15965.LC.29.1.wav
[60/1005] Processing: p15965.LC.3.45.wav
[61/1005] Processing: p15965.LC.30.123.wav
[62/1005] Processing: p15965.LC.31.99999.wav
[63/1005] Processing: p15965.LC.32.30.wav
[64/1005] Processing: p15965.LC.33.46.wav
[65/1005] Processing: p15965.LC.34.147.wav
[66/1005] Processing: p15965.LC.35.155.wav
[67/1005] Processing: p15965.LC.36.99999.wav
[68/1005] Processing: p15965.LC.38.63.wav
[69/1005] Processing: p15965.LC.4.81.wav
[70/1005] Processing: p15965.LC.41.99999.wav
[71/1005] Processing: p15965.LC.5.163.wav
[72/1005] Processing: p15965.LC.6.99999.wav
[73/1005] Processing: p15965.LC.7.66.wav
[74/1005] Processing: p15965.LC.9.129.wav
[75/1005] Processing: p15965.LW.11.99999.wav
[76/1005] Processing: p15965.LW.12.45.wav
[77/1005] Processing: p15965.LW.13.41.wav
[78/1005] Processing: p15965.LW.16.99999.wav
[79/1005] Processing: p15965.LW.17.134.wav
[80/1005] Processing: p15965.LW.18.118.wav
[81/1005] Processing: p15965.LW.19.67.wav
[82/1005] Processing: p15965.LW.2.155.wav
[83/1005] Processing: p15965.LW.20.63.wav
[84/1005] Processing: p15965.LW.21.99999.wav
[85/1005] Processing: p15965.LW.23.29.wav
[86/1005] Processing: p15965.LW.24.83.wav
[87/1005] Processing: p15965.LW.25.102.wav
[88/1005] Processing: p15965.LW.26.99999.wav
[89/1005] Processing: p15965.LW.27.36.wav
[90/1005] Processing: p15965.LW.28.69.wav
[91/1005] Processing: p15965.LW.3.122.wav
[92/1005] Processing: p15965.LW.30.163.wav
[93/1005] Processing: p15965.LW.31.99999.wav
[94/1005] Processing: p15965.LW.32.137.wav
[95/1005] Processing: p15965.LW.33.4.wav
[96/1005] Processing: p15965.LW.34.170.wav
[97/1005] Processing: p15965.LW.35.43.wav
[98/1005] Processing: p15965.LW.36.99999.wav
[99/1005] Processing: p15965.LW.37.138.wav
[100/1005] Processing: p15965.LW.38.47.wav
[101/1005] Processing: p15965.LW.39.65.wav
[102/1005] Processing: p15965.LW.4.116.wav
[103/1005] Processing: p15965.LW.40.95.wav
[104/1005] Processing: p15965.LW.41.99999.wav
[105/1005] Processing: p15965.LW.5.172.wav
[106/1005] Processing: p15965.LW.6.99999.wav
[107/1005] Processing: p15965.LW.7.153.wav
[108/1005] Processing: p15965.LW.8.32.wav
[109/1005] Processing: p15965.LW.9.160.wav
[110/1005] Processing: p15965.RC.1.44.wav
[111/1005] Processing: p15965.RC.10.155.wav
[112/1005] Processing: p15965.RC.11.99999.wav
[113/1005] Processing: p15965.RC.12.28.wav
[114/1005] Processing: p15965.RC.13.105.wav
[115/1005] Processing: p15965.RC.14.185.wav
[116/1005] Processing: p15965.RC.15.125.wav
[117/1005] Processing: p15965.RC.16.99999.wav
[118/1005] Processing: p15965.RC.17.47.wav
[119/1005] Processing: p15965.RC.18.56.wav
[120/1005] Processing: p15965.RC.19.31.wav
[121/1005] Processing: p15965.RC.2.121.wav
[122/1005] Processing: p15965.RC.20.99.wav
[123/1005] Processing: p15965.RC.21.99999.wav
[124/1005] Processing: p15965.RC.22.158.wav
[125/1005] Processing: p15965.RC.23.37.wav
[126/1005] Processing: p15965.RC.24.2.wav
[127/1005] Processing: p15965.RC.25.154.wav
[128/1005] Processing: p15965.RC.27.18.wav
[129/1005] Processing: p15965.RC.29.120.wav
[130/1005] Processing: p15965.RC.30.42.wav
[131/1005] Processing: p15965.RC.31.99999.wav
[132/1005] Processing: p15965.RC.32.76.wav
[133/1005] Processing: p15965.RC.33.104.wav
[134/1005] Processing: p15965.RC.34.39.wav
[135/1005] Processing: p15965.RC.35.72.wav
[136/1005] Processing: p15965.RC.36.99999.wav
[137/1005] Processing: p15965.RC.37.68.wav
[138/1005] Processing: p15965.RC.38.137.wav
[139/1005] Processing: p15965.RC.39.24.wav
[140/1005] Processing: p15965.RC.4.136.wav
[141/1005] Processing: p15965.RC.41.99999.wav
[142/1005] Processing: p15965.RC.5.53.wav
[143/1005] Processing: p15965.RC.6.99999.wav
[144/1005] Processing: p15965.RC.7.135.wav
[145/1005] Processing: p15965.RC.8.117.wav
[146/1005] Processing: p15965.RW.1.39.wav
[147/1005] Processing: p15965.RW.10.2.wav
[148/1005] Processing: p15965.RW.11.99999.wav
[149/1005] Processing: p15965.RW.12.61.wav
[150/1005] Processing: p15965.RW.14.112.wav
[151/1005] Processing: p15965.RW.15.106.wav
[152/1005] Processing: p15965.RW.17.183.wav
[153/1005] Processing: p15965.RW.18.151.wav
[154/1005] Processing: p15965.RW.19.140.wav
[155/1005] Processing: p15965.RW.2.181.wav
[156/1005] Processing: p15965.RW.20.161.wav
[157/1005] Processing: p15965.RW.21.99999.wav
[158/1005] Processing: p15965.RW.22.168.wav
[159/1005] Processing: p15965.RW.23.153.wav
[160/1005] Processing: p15965.RW.24.44.wav
[161/1005] Processing: p15965.RW.25.159.wav
[162/1005] Processing: p15965.RW.27.117.wav
[163/1005] Processing: p15965.RW.28.0.wav
[164/1005] Processing: p15965.RW.29.156.wav
[165/1005] Processing: p15965.RW.3.115.wav
[166/1005] Processing: p15965.RW.30.178.wav
[167/1005] Processing: p15965.RW.32.149.wav
[168/1005] Processing: p15965.RW.33.30.wav
[169/1005] Processing: p15965.RW.34.167.wav
[170/1005] Processing: p15965.RW.35.74.wav
[171/1005] Processing: p15965.RW.36.99999.wav
[172/1005] Processing: p15965.RW.37.67.wav
[173/1005] Processing: p15965.RW.38.76.wav
[174/1005] Processing: p15965.RW.39.137.wav
[175/1005] Processing: p15965.RW.4.68.wav
[176/1005] Processing: p15965.RW.40.107.wav
[177/1005] Processing: p15965.RW.41.99999.wav
[178/1005] Processing: p15965.RW.5.42.wav
[179/1005] Processing: p15965.RW.8.65.wav
[180/1005] Processing: p15965.RW.9.49.wav
[181/1005] Processing: p18785.LC.1.123.wav
[182/1005] Processing: p18785.LC.13.38.wav
[183/1005] Processing: p18785.LC.14.143.wav
[184/1005] Processing: p18785.LC.4.100.wav
[185/1005] Processing: p18785.LC.6.99999.wav
[186/1005] Processing: p18785.LC.7.13.wav
[187/1005] Processing: p18785.LC.8.175.wav
[188/1005] Processing: p18785.LW.11.99999.wav
[189/1005] Processing: p18785.LW.19.97.wav
[190/1005] Processing: p18785.RC.1.31.wav
[191/1005] Processing: p18785.RC.12.77.wav
[192/1005] Processing: p18785.RC.13.18.wav
[193/1005] Processing: p18785.RC.15.96.wav
[194/1005] Processing: p18785.RC.2.187.wav
[195/1005] Processing: p18785.RC.3.103.wav
[196/1005] Processing: p18785.RC.4.63.wav
[197/1005] Processing: p18785.RC.5.24.wav
[198/1005] Processing: p18785.RW.12.58.wav
[199/1005] Processing: p18785.RW.15.165.wav
[200/1005] Processing: p18785.RW.16.99999.wav
[201/1005] Processing: p18785.RW.19.131.wav
[202/1005] Processing: p18785.RW.21.99999.wav
[203/1005] Processing: p18785.RW.26.99999.wav
[204/1005] Processing: p18785.RW.28.102.wav
[205/1005] Processing: p18785.RW.9.5.wav
[206/1005] Processing: p20960.LC.1.185.wav
[207/1005] Processing: p20960.LC.11.99999.wav
[208/1005] Processing: p20960.LC.12.92.wav
[209/1005] Processing: p20960.LC.13.43.wav
[210/1005] Processing: p20960.LC.14.18.wav
[211/1005] Processing: p20960.LC.15.141.wav
[212/1005] Processing: p20960.LC.19.6.wav
[213/1005] Processing: p20960.LC.2.84.wav
[214/1005] Processing: p20960.LC.20.120.wav
[215/1005] Processing: p20960.LC.23.37.wav
[216/1005] Processing: p20960.LC.24.25.wav
[217/1005] Processing: p20960.LC.27.140.wav
[218/1005] Processing: p20960.LC.28.83.wav
[219/1005] Processing: p20960.LC.29.182.wav
[220/1005] Processing: p20960.LC.3.40.wav
[221/1005] Processing: p20960.LC.30.128.wav
[222/1005] Processing: p20960.LC.31.99999.wav
[223/1005] Processing: p20960.LC.32.151.wav
[224/1005] Processing: p20960.LC.33.137.wav
[225/1005] Processing: p20960.LC.34.176.wav
[226/1005] Processing: p20960.LC.35.186.wav
[227/1005] Processing: p20960.LC.6.99999.wav
[228/1005] Processing: p20960.LC.7.1.wav
[229/1005] Processing: p20960.LW.19.31.wav
[230/1005] Processing: p20960.LW.5.165.wav
[231/1005] Processing: p20960.RC.13.88.wav
[232/1005] Processing: p20960.RC.16.99999.wav
[233/1005] Processing: p20960.RC.17.77.wav
[234/1005] Processing: p20960.RC.19.104.wav
[235/1005] Processing: p20960.RC.20.178.wav
[236/1005] Processing: p20960.RC.22.33.wav
[237/1005] Processing: p20960.RC.23.47.wav
[238/1005] Processing: p20960.RC.25.63.wav
[239/1005] Processing: p20960.RC.26.99999.wav
[240/1005] Processing: p20960.RC.27.56.wav
[241/1005] Processing: p20960.RC.28.58.wav
[242/1005] Processing: p20960.RC.30.143.wav
[243/1005] Processing: p20960.RC.31.99999.wav
[244/1005] Processing: p20960.RC.32.109.wav
[245/1005] Processing: p20960.RC.33.22.wav
[246/1005] Processing: p20960.RC.35.121.wav
[247/1005] Processing: p20960.RC.5.16.wav
[248/1005] Processing: p20960.RC.7.142.wav
[249/1005] Processing: p20960.RW.10.17.wav
[250/1005] Processing: p20960.RW.25.88.wav
[251/1005] Processing: p28030.LC.10.63.wav
[252/1005] Processing: p28030.LC.2.59.wav
[253/1005] Processing: p28030.LC.20.17.wav
[254/1005] Processing: p28030.LC.3.133.wav
[255/1005] Processing: p28030.LC.31.99999.wav
[256/1005] Processing: p28030.LC.5.23.wav
[257/1005] Processing: p28030.LC.7.86.wav
[258/1005] Processing: p28030.LC.8.188.wav
[259/1005] Processing: p28030.LC.9.12.wav
[260/1005] Processing: p28030.LW.15.107.wav
[261/1005] Processing: p28030.LW.16.99999.wav
[262/1005] Processing: p28030.LW.18.53.wav
[263/1005] Processing: p28030.LW.20.50.wav
[264/1005] Processing: p28030.RC.1.86.wav
[265/1005] Processing: p28030.RC.13.22.wav
[266/1005] Processing: p28030.RC.18.45.wav
[267/1005] Processing: p28030.RC.19.51.wav
[268/1005] Processing: p28030.RC.26.99999.wav
[269/1005] Processing: p28030.RC.29.39.wav
[270/1005] Processing: p28030.RC.3.7.wav
[271/1005] Processing: p28030.RC.30.118.wav
[272/1005] Processing: p28030.RC.33.152.wav
[273/1005] Processing: p28030.RC.36.99999.wav
[274/1005] Processing: p28030.RC.4.66.wav
[275/1005] Processing: p28030.RC.5.178.wav
[276/1005] Processing: p28030.RC.6.99999.wav
[277/1005] Processing: p28030.RW.13.175.wav
[278/1005] Processing: p28030.RW.16.99999.wav
[279/1005] Processing: p28030.RW.28.177.wav
[280/1005] Processing: p37540.LC.10.24.wav
[281/1005] Processing: p37540.LC.14.32.wav
[282/1005] Processing: p37540.LC.15.185.wav
[283/1005] Processing: p37540.LC.17.128.wav
[284/1005] Processing: p37540.LC.20.67.wav
[285/1005] Processing: p37540.LC.25.121.wav
[286/1005] Processing: p37540.LC.29.87.wav
[287/1005] Processing: p37540.LC.31.99999.wav
[288/1005] Processing: p37540.LC.33.166.wav
[289/1005] Processing: p37540.LC.34.30.wav
[290/1005] Processing: p37540.LC.35.48.wav
[291/1005] Processing: p37540.LC.36.99999.wav
[292/1005] Processing: p37540.LC.4.90.wav
[293/1005] Processing: p37540.LC.9.112.wav
[294/1005] Processing: p37540.LW.15.168.wav
[295/1005] Processing: p37540.LW.21.99999.wav
[296/1005] Processing: p37540.RC.11.99999.wav
[297/1005] Processing: p37540.RC.16.99999.wav
[298/1005] Processing: p37540.RC.17.131.wav
[299/1005] Processing: p37540.RC.18.186.wav
[300/1005] Processing: p37540.RC.21.99999.wav
[301/1005] Processing: p37540.RC.22.138.wav
[302/1005] Processing: p37540.RC.27.35.wav
[303/1005] Processing: p37540.RC.28.187.wav
[304/1005] Processing: p37540.RC.29.154.wav
[305/1005] Processing: p37540.RC.3.182.wav
[306/1005] Processing: p37540.RC.30.91.wav
[307/1005] Processing: p37540.RC.31.99999.wav
[308/1005] Processing: p37540.RC.32.119.wav
[309/1005] Processing: p37540.RC.33.93.wav
[310/1005] Processing: p37540.RC.36.99999.wav
[311/1005] Processing: p37540.RC.4.36.wav
[312/1005] Processing: p37540.RC.5.89.wav
[313/1005] Processing: p37540.RW.10.18.wav
[314/1005] Processing: p37540.RW.13.0.wav
[315/1005] Processing: p37540.RW.16.99999.wav
[316/1005] Processing: p37540.RW.25.135.wav
[317/1005] Processing: p37540.RW.36.99999.wav
[318/1005] Processing: p37540.RW.6.99999.wav
[319/1005] Processing: p37540.RW.9.30.wav
[320/1005] Processing: p59520.LC.1.148.wav
[321/1005] Processing: p59520.LC.10.66.wav
[322/1005] Processing: p59520.LC.12.181.wav
[323/1005] Processing: p59520.LC.13.107.wav
[324/1005] Processing: p59520.LC.14.153.wav
[325/1005] Processing: p59520.LC.15.47.wav
[326/1005] Processing: p59520.LC.16.99999.wav
[327/1005] Processing: p59520.LC.19.101.wav
[328/1005] Processing: p59520.LC.2.60.wav
[329/1005] Processing: p59520.LC.20.177.wav
[330/1005] Processing: p59520.LC.22.152.wav
[331/1005] Processing: p59520.LC.27.33.wav
[332/1005] Processing: p59520.LC.29.63.wav
[333/1005] Processing: p59520.LC.3.86.wav
[334/1005] Processing: p59520.LC.30.114.wav
[335/1005] Processing: p59520.LC.36.99999.wav
[336/1005] Processing: p59520.LC.4.137.wav
[337/1005] Processing: p59520.LC.5.140.wav
[338/1005] Processing: p59520.LC.6.99999.wav
[339/1005] Processing: p59520.LC.7.186.wav
[340/1005] Processing: p59520.LW.14.72.wav
[341/1005] Processing: p59520.LW.35.136.wav
[342/1005] Processing: p59520.LW.8.17.wav
[343/1005] Processing: p59520.RC.1.121.wav
[344/1005] Processing: p59520.RC.11.99999.wav
[345/1005] Processing: p59520.RC.12.8.wav
[346/1005] Processing: p59520.RC.14.162.wav
[347/1005] Processing: p59520.RC.2.156.wav
[348/1005] Processing: p59520.RC.21.99999.wav
[349/1005] Processing: p59520.RC.22.10.wav
[350/1005] Processing: p59520.RC.23.34.wav
[351/1005] Processing: p59520.RC.24.58.wav
[352/1005] Processing: p59520.RC.25.126.wav
[353/1005] Processing: p59520.RC.26.99999.wav
[354/1005] Processing: p59520.RC.28.57.wav
[355/1005] Processing: p59520.RC.29.184.wav
[356/1005] Processing: p59520.RC.3.13.wav
[357/1005] Processing: p59520.RC.32.30.wav
[358/1005] Processing: p59520.RC.33.71.wav
[359/1005] Processing: p59520.RC.34.174.wav
[360/1005] Processing: p59520.RC.35.76.wav
[361/1005] Processing: p59520.RC.36.99999.wav
[362/1005] Processing: p59520.RC.4.47.wav
[363/1005] Processing: p59520.RC.5.112.wav
[364/1005] Processing: p59520.RC.7.95.wav
[365/1005] Processing: p59520.RC.9.166.wav
[366/1005] Processing: p59520.RW.10.82.wav
[367/1005] Processing: p59520.RW.16.99999.wav
[368/1005] Processing: p59520.RW.17.74.wav
[369/1005] Processing: p59520.RW.24.130.wav
[370/1005] Processing: p59520.RW.25.79.wav
[371/1005] Processing: p59520.RW.3.66.wav
[372/1005] Processing: p59520.RW.34.156.wav
[373/1005] Processing: p60145.LC.11.99999.wav
[374/1005] Processing: p60145.LC.12.31.wav
[375/1005] Processing: p60145.LC.14.50.wav
[376/1005] Processing: p60145.LC.15.147.wav
[377/1005] Processing: p60145.LC.16.99999.wav
[378/1005] Processing: p60145.LC.17.32.wav
[379/1005] Processing: p60145.LC.21.99999.wav
[380/1005] Processing: p60145.LC.22.104.wav
[381/1005] Processing: p60145.LC.23.169.wav
[382/1005] Processing: p60145.LC.25.173.wav
[383/1005] Processing: p60145.LC.26.99999.wav
[384/1005] Processing: p60145.LC.28.175.wav
[385/1005] Processing: p60145.LC.32.53.wav
[386/1005] Processing: p60145.LC.33.40.wav
[387/1005] Processing: p60145.LC.34.30.wav
[388/1005] Processing: p60145.LC.35.92.wav
[389/1005] Processing: p60145.LC.36.99999.wav
[390/1005] Processing: p60145.LC.37.33.wav
[391/1005] Processing: p60145.LC.39.28.wav
[392/1005] Processing: p60145.LC.4.131.wav
[393/1005] Processing: p60145.LC.7.119.wav
[394/1005] Processing: p60145.LW.11.99999.wav
[395/1005] Processing: p60145.LW.17.113.wav
[396/1005] Processing: p60145.LW.27.18.wav
[397/1005] Processing: p60145.LW.31.99999.wav
[398/1005] Processing: p60145.LW.33.141.wav
[399/1005] Processing: p60145.LW.38.118.wav
[400/1005] Processing: p60145.LW.4.105.wav
[401/1005] Processing: p60145.LW.41.99999.wav
[402/1005] Processing: p60145.RC.11.99999.wav
[403/1005] Processing: p60145.RC.14.162.wav
[404/1005] Processing: p60145.RC.19.35.wav
[405/1005] Processing: p60145.RC.20.90.wav
[406/1005] Processing: p60145.RC.21.99999.wav
[407/1005] Processing: p60145.RC.22.97.wav
[408/1005] Processing: p60145.RC.23.123.wav
[409/1005] Processing: p60145.RC.24.113.wav
[410/1005] Processing: p60145.RC.25.61.wav
[411/1005] Processing: p60145.RC.26.99999.wav
[412/1005] Processing: p60145.RC.27.136.wav
[413/1005] Processing: p60145.RC.28.58.wav
[414/1005] Processing: p60145.RC.3.18.wav
[415/1005] Processing: p60145.RC.30.78.wav
[416/1005] Processing: p60145.RC.33.34.wav
[417/1005] Processing: p60145.RC.35.39.wav
[418/1005] Processing: p60145.RC.36.99999.wav
[419/1005] Processing: p60145.RC.8.3.wav
[420/1005] Processing: p60145.RC.9.8.wav
[421/1005] Processing: p60145.RW.12.145.wav
[422/1005] Processing: p60145.RW.17.186.wav
[423/1005] Processing: p60145.RW.24.5.wav
[424/1005] Processing: p60145.RW.34.100.wav
[425/1005] Processing: p60145.RW.41.99999.wav
[426/1005] Processing: p60145.RW.7.27.wav
[427/1005] Processing: p62650.LW.11.99999.wav
[428/1005] Processing: p62650.LW.16.99999.wav
[429/1005] Processing: p62650.LW.18.2.wav
[430/1005] Processing: p62650.LW.2.99.wav
[431/1005] Processing: p62650.LW.20.68.wav
[432/1005] Processing: p62650.LW.25.183.wav
[433/1005] Processing: p62650.LW.3.19.wav
[434/1005] Processing: p62650.RC.1.165.wav
[435/1005] Processing: p62650.RC.10.47.wav
[436/1005] Processing: p62650.RC.11.99999.wav
[437/1005] Processing: p62650.RC.12.26.wav
[438/1005] Processing: p62650.RC.14.6.wav
[439/1005] Processing: p62650.RC.16.99999.wav
[440/1005] Processing: p62650.RC.17.60.wav
[441/1005] Processing: p62650.RC.18.48.wav
[442/1005] Processing: p62650.RC.19.180.wav
[443/1005] Processing: p62650.RC.2.125.wav
[444/1005] Processing: p62650.RC.20.42.wav
[445/1005] Processing: p62650.RC.21.99999.wav
[446/1005] Processing: p62650.RC.23.101.wav
[447/1005] Processing: p62650.RC.24.51.wav
[448/1005] Processing: p62650.RC.25.46.wav
[449/1005] Processing: p62650.RC.26.99999.wav
[450/1005] Processing: p62650.RC.27.34.wav
[451/1005] Processing: p62650.RC.28.86.wav
[452/1005] Processing: p62650.RC.3.19.wav
[453/1005] Processing: p62650.RC.30.155.wav
[454/1005] Processing: p62650.RC.31.99999.wav
[455/1005] Processing: p62650.RC.4.138.wav
[456/1005] Processing: p62650.RC.5.16.wav
[457/1005] Processing: p62650.RC.6.99999.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,30.69626,0.263414,26.79136,33.90815,35.34398,...,-0.044108,0.001074,0.041798,3.759399,3.065134,0.090000,0.043012,0.191111,0.162716,-42.64029
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,35.56696,0.143081,35.00095,35.37488,38.83761,...,-0.043940,0.005591,0.040283,3.773585,3.381643,0.081429,0.039795,0.194286,0.175650,-41.84466
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.36375,0.038552,33.35062,34.00272,35.33639,...,-0.048299,0.003931,0.039338,3.083700,2.252252,0.138000,0.091957,0.236667,0.375751,-42.33194
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,29.84339,0.294958,14.93551,34.11028,36.57950,...,-0.036482,0.001783,0.039428,4.464286,4.566210,0.085000,0.065000,0.125555,0.134504,-43.16550
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,32.33361,0.226287,32.81301,33.89865,37.18299,...,-0.046075,0.004801,0.037588,2.966102,3.463203,0.087500,0.047368,0.178750,0.257849,-41.63815