In [3]:
from pathlib import Path
import subprocess
import pandas as pd
import tempfile

# Load
BASE_DIR = Path(r"C:\Users\marti\Documents\Technical Medicine Master\Stages TM2\TM2-3\Technische opdracht")

OPENSMILE_EXE = BASE_DIR / "tools" / "openSMILE" / "bin" / "SMILExtract.exe"
CONFIG_FILE = BASE_DIR / "tools" / "openSMILE" / "config" / "egemaps" / "v02" / "eGeMAPSv02.conf"

perturbation_sets = {
    "gaussian": {
        "input_root": BASE_DIR / "TAME" / "original_gaussian_noise_perturbations_pain",
        "folders": {
            "low_gaussian_noise": "low",
            "medium_gaussian_noise": "medium",
            "high_gaussian_noise": "high",
            "very_high_gaussian_noise": "very_high",
        }
    },
    "lowpass": {
        "input_root": BASE_DIR / "TAME" / "original_lowpass_perturbations_pain",
        "folders": {
            "low_lowpass": "low",
            "medium_lowpass": "medium",
            "high_lowpass": "high",
            "very_high_lowpass": "very_high",
        }
    },
    "pink": {
        "input_root": BASE_DIR / "TAME" / "original_pink_noise_perturbations_pain",
        "folders": {
            "low_pink_noise": "low",
            "medium_pink_noise": "medium",
            "high_pink_noise": "high",
            "very_high_pink_noise": "very_high",
        }
    },
    "intensity": {
        "input_root": BASE_DIR / "TAME" / "original_intensity_perturbations_pain",
        "folders": {
            "-6dB": "-6dB",
            "-3dB": "-3dB",
            "+3dB": "3dB",
            "+6dB": "6dB",
        }
    }
}


# Check main paths
print("SMILExtract exists:", OPENSMILE_EXE.exists())
print("Config exists:", CONFIG_FILE.exists())

if not OPENSMILE_EXE.exists():
    raise FileNotFoundError(f"SMILExtract.exe not found:\n{OPENSMILE_EXE}")

if not CONFIG_FILE.exists():
    raise FileNotFoundError(f"Config file not found:\n{CONFIG_FILE}")


def extract_opensmile_features(audio_root, output_features_csv, output_failed_csv):
    print(f"\n--- Processing folder: {audio_root.name} ---")

    if not audio_root.exists():
        raise FileNotFoundError(f"Audio root not found:\n{audio_root}")

    wav_files = sorted(audio_root.rglob("*.wav"))
    print(f"Number of wav files found: {len(wav_files)}")

    if len(wav_files) == 0:
        raise ValueError(f"No .wav files found in:\n{audio_root}")

    all_rows = []
    failed_files = []

    for i, wav_file in enumerate(wav_files, start=1):
        print(f"[{i}/{len(wav_files)}] Processing: {wav_file.name}")

        participant_id = wav_file.parent.name
        filename = wav_file.name

        with tempfile.NamedTemporaryFile(suffix=".csv", delete=False) as tmp:
            temp_output_csv = Path(tmp.name)

        try:
            temp_output_csv.unlink(missing_ok=True)

            cmd = [
                str(OPENSMILE_EXE),
                "-C", str(CONFIG_FILE),
                "-I", str(wav_file),
                "-csvoutput", str(temp_output_csv),
            ]

            result = subprocess.run(cmd, capture_output=True, text=True)

            if result.returncode != 0:
                failed_files.append({
                    "participant_id": participant_id,
                    "filename": filename,
                    "file_path": str(wav_file),
                    "reason": "openSMILE return code != 0",
                    "stderr": result.stderr
                })
                continue

            if not temp_output_csv.exists():
                failed_files.append({
                    "participant_id": participant_id,
                    "filename": filename,
                    "file_path": str(wav_file),
                    "reason": "no output made",
                    "stderr": result.stderr
                })
                continue

            try:
                feature_df = pd.read_csv(temp_output_csv, sep=";", engine="python")
            except Exception as e:
                failed_files.append({
                    "participant_id": participant_id,
                    "filename": filename,
                    "file_path": str(wav_file),
                    "reason": f"error in csv: {e}",
                    "stderr": result.stderr
                })
                continue

            if feature_df.empty:
                failed_files.append({
                    "participant_id": participant_id,
                    "filename": filename,
                    "file_path": str(wav_file),
                    "reason": "output csv is empty",
                    "stderr": result.stderr
                })
                continue

            row = feature_df.iloc[0].to_dict()
            row["name"] = filename
            row["participant_id"] = participant_id
            row["filename"] = filename
            row["file_path"] = str(wav_file)

            all_rows.append(row)

        except Exception as e:
            failed_files.append({
                "participant_id": participant_id,
                "filename": filename,
                "file_path": str(wav_file),
                "reason": f"error: {e}",
                "stderr": ""
            })

        finally:
            temp_output_csv.unlink(missing_ok=True)

    features_df = pd.DataFrame(all_rows)

    preferred_front_cols = ["participant_id", "filename", "file_path", "name", "frameTime"]
    remaining_cols = [col for col in features_df.columns if col not in preferred_front_cols]
    features_df = features_df[
        [col for col in preferred_front_cols if col in features_df.columns] + remaining_cols
    ]

    features_df.to_csv(output_features_csv, index=False)

    print("\nDone.")
    print("Number of successful feature rows:", len(features_df))
    print("Number of failed files:", len(failed_files))
    print("Features saved in:")
    print(output_features_csv)

    if failed_files:
        failed_df = pd.DataFrame(failed_files)
        failed_df.to_csv(output_failed_csv, index=False)
        print("\nFailed files saved in:")
        print(output_failed_csv)

    print("\nShape features dataframe:", features_df.shape)
    display(features_df.head())

    return features_df, failed_files


results = {}

for perturbation_type, settings in perturbation_sets.items():
    input_root = settings["input_root"]
    folder_dict = settings["folders"]

    print(f"\n========== {perturbation_type.upper()} ==========")

    if not input_root.exists():
        raise FileNotFoundError(f"Input root not found:\n{input_root}")

    results[perturbation_type] = {}

    for folder_name, label in folder_dict.items():
        audio_root = input_root / folder_name
        output_features_csv = BASE_DIR / f"opensmile_{label}_{perturbation_type}_features_pain_original.csv"
        output_failed_csv = BASE_DIR / f"opensmile_{label}_{perturbation_type}_failed_files_original.csv"

        features_df, failed_files = extract_opensmile_features(
            audio_root=audio_root,
            output_features_csv=output_features_csv,
            output_failed_csv=output_failed_csv
        )

        results[perturbation_type][label] = {
            "features_df": features_df,
            "failed_files": failed_files
        }

SMILExtract exists: True
Config exists: True

========== GAUSSIAN ==========

--- Processing folder: low_gaussian_noise ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01972,0.058435,32.85036,34.98619,36.56318,...,-0.021520,-0.012841,0.097341,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-34.59005
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.45998,0.054271,35.04662,35.46388,38.76064,...,-0.021852,-0.009274,0.094646,4.245283,2.415459,0.140000,0.077974,0.254000,0.238462,-33.72906
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.32712,0.041923,33.18603,33.72223,35.32508,...,-0.024862,-0.010828,0.097585,3.524229,2.252252,0.196000,0.151737,0.226000,0.256094,-34.10008
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.30899,0.110528,33.53381,34.41047,36.70740,...,-0.014014,-0.017034,0.092545,4.017857,3.196347,0.127143,0.137811,0.165714,0.139577,-35.13419
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.14941,0.062769,33.52361,34.20158,37.36217,...,-0.023645,-0.010545,0.083708,2.966102,2.164502,0.180000,0.093595,0.258000,0.288056,-33.76992

--- Processing folder: medium_gaussian_noise ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01963,0.058427,32.85281,34.98716,36.55990,...,-0.021387,-0.012282,0.097348,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-34.58901
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.45993,0.054263,35.04636,35.46710,38.76003,...,-0.021831,-0.007673,0.094656,4.245283,2.415459,0.140000,0.077974,0.254000,0.238462,-33.72681
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.32726,0.041923,33.18813,33.72217,35.32865,...,-0.024739,-0.009688,0.097607,3.524229,2.252252,0.196000,0.151737,0.226000,0.256094,-34.09967
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.32080,0.111096,33.58875,34.40994,36.71550,...,-0.014000,-0.015939,0.092258,4.464286,3.196347,0.125714,0.136994,0.167143,0.142900,-35.13229
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.16417,0.062969,33.51703,34.20614,37.38025,...,-0.023814,-0.009232,0.083802,2.966102,2.164502,0.178000,0.093467,0.260000,0.287193,-33.76760

--- Processing folder: high_gaussian_noise ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01975,0.058421,32.85313,34.98592,36.55469,...,-0.021637,-0.009547,0.097749,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-34.58113
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.46059,0.054252,35.04646,35.46669,38.76212,...,-0.021516,-0.005002,0.095170,4.245283,2.415459,0.140000,0.077974,0.254000,0.238462,-33.72016
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.32722,0.041959,33.18671,33.72104,35.33396,...,-0.024903,-0.006890,0.097988,3.524229,2.252252,0.196000,0.151737,0.226000,0.256094,-34.08922
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.96259,0.039958,33.75467,34.41735,36.74244,...,-0.014707,-0.013026,0.091427,4.464286,2.739726,0.143333,0.140436,0.201667,0.218816,-35.12506
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.18016,0.063128,33.51025,34.20992,37.39881,...,-0.023480,-0.006725,0.083855,2.966102,2.164502,0.176000,0.096042,0.262000,0.285755,-33.76162

--- Processing folder: very_high_gaussian_noise ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.02321,0.058728,32.84606,35.00917,36.74461,...,-0.021018,-0.006738,0.098886,3.759399,3.065134,0.106250,0.046620,0.176667,0.171400,-34.54845
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.55996,0.055769,35.04079,35.50241,38.83339,...,-0.019943,-0.001934,0.096788,4.245283,2.898551,0.110000,0.040415,0.215000,0.233791,-33.68541
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.27246,0.040404,33.18272,33.69941,35.29228,...,-0.023374,-0.003534,0.099678,3.524229,2.252252,0.192000,0.152761,0.228000,0.255453,-34.05143
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.96769,0.040093,33.75418,34.42307,36.75798,...,-0.014135,-0.009636,0.092099,4.464286,2.739726,0.141667,0.140998,0.203333,0.218225,-35.08837
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.08252,0.064887,33.20381,34.18412,37.40409,...,-0.023010,-0.002825,0.088584,2.966102,3.030303,0.122857,0.067340,0.184286,0.187910,-33.72935

========== LOWPASS ==========

--- Processing folder: low_lowpass ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01982,0.058435,32.85139,34.98654,36.56283,...,-0.021509,-0.012967,0.097348,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-34.59064
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.45981,0.054269,35.04673,35.46411,38.76053,...,-0.021835,-0.009162,0.094619,4.245283,2.415459,0.140000,0.077974,0.254000,0.238462,-33.73340
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.32715,0.041927,33.18597,33.72219,35.32590,...,-0.024855,-0.010969,0.097578,3.524229,2.252252,0.196000,0.151737,0.226000,0.256094,-34.10119
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.30878,0.110540,33.53382,34.41002,36.70712,...,-0.014004,-0.016952,0.092545,4.017857,3.196347,0.127143,0.137811,0.165714,0.139577,-35.13579
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.14962,0.062774,33.52359,34.20146,37.36137,...,-0.023647,-0.010636,0.083693,2.966102,2.164502,0.180000,0.093595,0.258000,0.288056,-33.77250

--- Processing folder: medium_lowpass ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01981,0.058436,32.85075,34.98674,36.56274,...,-0.021508,-0.012971,0.097305,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-34.59188
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.45980,0.054268,35.04667,35.46409,38.76047,...,-0.021835,-0.009178,0.094440,4.245283,2.415459,0.140000,0.077974,0.254000,0.238462,-33.73729
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.32710,0.041926,33.18599,33.72219,35.32578,...,-0.024857,-0.010975,0.097553,3.524229,2.252252,0.196000,0.151737,0.226000,0.256094,-34.10219
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.30880,0.110537,33.53381,34.41002,36.70700,...,-0.014004,-0.016970,0.092494,4.017857,3.196347,0.127143,0.137811,0.165714,0.139577,-35.13731
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.13585,0.062588,33.53019,34.20141,37.34263,...,-0.023574,-0.010669,0.083705,2.966102,2.164502,0.182000,0.093894,0.256000,0.288971,-33.77543

--- Processing folder: high_lowpass ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01982,0.058439,32.85063,34.98684,36.56267,...,-0.021506,-0.012968,0.097175,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-34.59435
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.45980,0.054268,35.04673,35.46419,38.76056,...,-0.021832,-0.009148,0.093984,4.245283,2.415459,0.140000,0.077974,0.254000,0.238462,-33.74162
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.31649,0.041856,33.18868,33.70975,35.32401,...,-0.024949,-0.010749,0.097167,3.524229,2.252252,0.198000,0.155229,0.224000,0.257418,-34.10500
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.30872,0.110540,33.53382,34.41003,36.70718,...,-0.014006,-0.016954,0.092313,4.017857,3.196347,0.127143,0.137811,0.165714,0.139577,-35.14093
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.13580,0.062586,33.53017,34.20140,37.34267,...,-0.023572,-0.010666,0.083623,2.966102,2.164502,0.182000,0.093894,0.256000,0.288971,-33.77701

--- Processing folder: very_high_lowpass ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01984,0.058456,32.84958,34.98623,36.56284,...,-0.021509,-0.012988,0.097011,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-34.59946
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.45993,0.054268,35.04671,35.46512,38.76234,...,-0.021839,-0.009151,0.093764,3.301887,2.415459,0.140000,0.077974,0.254000,0.238462,-33.74923
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.31607,0.041851,33.18906,33.70975,35.32336,...,-0.024946,-0.010764,0.096975,3.524229,2.252252,0.198000,0.155229,0.224000,0.257418,-34.11530
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.30882,0.110542,33.53359,34.40994,36.70774,...,-0.014003,-0.016965,0.091884,4.017857,3.196347,0.127143,0.137811,0.165714,0.139577,-35.15170
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.04971,0.063331,33.29409,34.17381,37.34068,...,-0.024020,-0.010187,0.083193,2.966102,2.597403,0.155000,0.104841,0.206667,0.188562,-33.78149

========== PINK ==========

--- Processing folder: low_pink_noise ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01976,0.058432,32.85154,34.98602,36.56184,...,-0.021459,-0.012978,0.097437,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-34.59024
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.45974,0.054270,35.04661,35.46396,38.76054,...,-0.021822,-0.008995,0.094611,4.245283,2.415459,0.140000,0.077974,0.254000,0.238462,-33.72975
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.32708,0.041926,33.18596,33.72218,35.32517,...,-0.024789,-0.011026,0.097550,3.524229,2.252252,0.196000,0.151737,0.226000,0.256094,-34.10025
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.30886,0.110546,33.53389,34.41005,36.70704,...,-0.014162,-0.016890,0.092532,4.017857,3.196347,0.127143,0.137811,0.165714,0.139577,-35.13380
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.14952,0.062774,33.52357,34.20142,37.36095,...,-0.023640,-0.010674,0.083669,2.966102,2.164502,0.180000,0.093595,0.258000,0.288056,-33.77028

--- Processing folder: medium_pink_noise ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.02314,0.058739,32.84738,35.02186,36.75265,...,-0.021593,-0.012736,0.097417,3.759399,3.065134,0.106250,0.046620,0.176667,0.171400,-34.58976
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.50160,0.054746,35.04873,35.48957,38.80389,...,-0.021948,-0.008670,0.094497,4.245283,2.415459,0.142000,0.076785,0.252000,0.239533,-33.73071
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.31588,0.041864,33.18445,33.70949,35.32366,...,-0.024754,-0.010153,0.096634,3.524229,2.252252,0.198000,0.155229,0.224000,0.257418,-34.10139
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.30840,0.110541,33.53405,34.41001,36.70555,...,-0.013628,-0.016150,0.092410,4.017857,3.196347,0.127143,0.137811,0.165714,0.139577,-35.13268
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.16436,0.062964,33.51719,34.20773,37.37939,...,-0.023621,-0.010115,0.083931,2.966102,2.164502,0.178000,0.093467,0.260000,0.287193,-33.77149

--- Processing folder: high_pink_noise ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01525,0.058154,32.85791,34.97415,36.37626,...,-0.021249,-0.011227,0.097079,3.759399,3.065134,0.108750,0.048332,0.174444,0.172891,-34.58636
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.49791,0.055131,35.04088,35.45159,38.79257,...,-0.020314,-0.006595,0.096791,4.245283,2.898551,0.110000,0.043205,0.215000,0.234503,-33.70999
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.30433,0.041921,33.18400,33.69855,35.30797,...,-0.023940,-0.008187,0.097552,3.524229,2.252252,0.196000,0.154350,0.224000,0.257418,-34.09402
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.96227,0.039942,33.75480,34.41716,36.74198,...,-0.014622,-0.014810,0.091780,4.464286,2.739726,0.143333,0.140436,0.201667,0.218816,-35.11421
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.08201,0.063533,33.28917,34.20089,37.34243,...,-0.024211,-0.008234,0.084127,2.966102,2.597403,0.151667,0.103669,0.210000,0.191224,-33.75700

--- Processing folder: very_high_pink_noise ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.02153,0.058359,32.84982,34.99692,36.55466,...,-0.022363,-0.009667,0.098923,3.759399,3.065134,0.1075,0.047368,0.175556,0.174618,-34.53739
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.46101,0.054289,35.04647,35.46592,38.76034,...,-0.022897,-0.004102,0.095261,4.245283,2.415459,0.1400,0.077974,0.254000,0.238462,-33.68469
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.22300,0.038710,33.17823,33.65977,35.28429,...,-0.024428,-0.004913,0.097822,3.524229,2.252252,0.1920,0.158291,0.228000,0.255374,-34.04326
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.94257,0.040123,33.68503,34.41588,36.73630,...,-0.014845,-0.012298,0.092611,4.464286,2.739726,0.1450,0.141156,0.200000,0.215174,-35.08847
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.19194,0.063509,33.51077,34.23636,37.40177,...,-0.025671,-0.005291,0.084302,2.966102,2.164502,0.1760,0.099318,0.220000,0.276586,-33.70619

========== INTENSITY ==========

--- Processing folder: -6dB ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01979,0.058435,32.85075,34.98679,36.56271,...,-0.016694,-0.009652,0.048743,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-40.59483
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.45984,0.054269,35.04668,35.46415,38.76050,...,-0.017030,-0.005880,0.047378,4.245283,2.415459,0.140000,0.077974,0.254000,0.238462,-39.73326
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.32711,0.041927,33.18595,33.72218,35.32600,...,-0.020040,-0.007690,0.048857,3.524229,2.252252,0.196000,0.151737,0.226000,0.256094,-40.10503
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.30875,0.110542,33.53381,34.41003,36.70716,...,-0.009189,-0.013676,0.046335,4.017857,3.196347,0.127143,0.137811,0.165714,0.139577,-41.13942
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.14966,0.062776,33.52360,34.20155,37.36126,...,-0.018824,-0.007371,0.041902,2.966102,2.164502,0.180000,0.093595,0.258000,0.288056,-39.77417

--- Processing folder: -3dB ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01982,0.058435,32.85137,34.98691,36.56270,...,-0.019098,-0.011328,0.068892,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-37.59200
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.45982,0.054269,35.04666,35.46404,38.76054,...,-0.019442,-0.007535,0.066964,4.245283,2.415459,0.140000,0.077974,0.254000,0.238462,-36.73072
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.32711,0.041927,33.18596,33.72219,35.32539,...,-0.022452,-0.009344,0.069053,3.524229,2.252252,0.196000,0.151737,0.226000,0.256094,-37.10236
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.30878,0.110532,33.53381,34.41002,36.70700,...,-0.011595,-0.015316,0.065491,4.017857,3.196347,0.127143,0.137811,0.165714,0.139577,-38.13634
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.14958,0.062773,33.52359,34.20160,37.36095,...,-0.021253,-0.009010,0.059224,2.966102,2.164502,0.180000,0.093595,0.258000,0.288056,-36.77179

--- Processing folder: +3dB ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01982,0.058435,32.85135,34.98661,36.56275,...,-0.023911,-0.014601,0.137553,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-31.58870
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.45980,0.054268,35.04674,35.46412,38.76046,...,-0.024243,-0.010789,0.133698,4.245283,2.415459,0.140000,0.077974,0.254000,0.238462,-30.72772
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.32709,0.041926,33.18596,33.72220,35.32523,...,-0.027261,-0.012615,0.137877,3.524229,2.252252,0.196000,0.151737,0.226000,0.256094,-31.09913
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.30872,0.110542,33.53382,34.41000,36.70711,...,-0.016414,-0.018602,0.130766,4.017857,3.196347,0.127143,0.137811,0.165714,0.139577,-32.13254
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.14965,0.062775,33.52358,34.20151,37.36132,...,-0.026046,-0.012304,0.118262,2.966102,2.164502,0.180000,0.093595,0.258000,0.288056,-30.76879

--- Processing folder: +6dB ---
Number of wav files found: 1055
[1/1055] Processing: p10085.LC.1.161.wav
[2/1055] Processing: p10085.LC.12.59.wav
[3/1055] Processing: p10085.LC.14.45.wav
[4/1055] Processing: p10085.LC.18.41.wav
[5/1055] Processing: p10085.LC.2.106.wav
[6/1055] Processing: p10085.LC.23.156.wav
[7/1055] Processing: p10085.LC.24.172.wav
[8/1055] Processing: p10085.LC.26.99999.wav
[9/1055] Processing: p10085.LC.3.60.wav
[10/1055] Processing: p10085.LC.30.132.wav
[11/1055] Processing: p10085.LC.31.99999.wav
[12/1055] Processing: p10085.LC.33.6.wav
[13/1055] Processing: p10085.LC.34.122.wav
[14/1055] Processing: p10085.LC.37.71.wav
[15/1055] Processing: p10085.LC.38.160.wav
[16/1055] Processing: p10085.LC.4.76.wav
[17/1055] Processing: p10085.LC.40.174.wav
[18/1055] Processing: p10085.LC.41.99999.wav
[19/1055] Processing: p10085.LC.5.134.wav
[20/1055] Processing: p10085.LC.6.99999.wav
[21/1055] Processing: p10085.LC.7.62.wav
[22/1055] Processing: p10085.LC.9.55.wav
[23/1055] Processing: p10085.LW.28.85.wav
[24/1055] Processing: p10085.LW.36.99999.wav
[25/1055] Processing: p10085.RC.11.99999.wav
[26/1055] Processing: p10085.RC.12.165.wav
[27/1055] Processing: p10085.RC.13.36.wav
[28/1055] Processing: p10085.RC.14.86.wav
[29/1055] Processing: p10085.RC.16.99999.wav
[30/1055] Processing: p10085.RC.17.160.wav
[31/1055] Processing: p10085.RC.19.78.wav
[32/1055] Processing: p10085.RC.20.79.wav
[33/1055] Processing: p10085.RC.26.99999.wav
[34/1055] Processing: p10085.RC.28.52.wav
[35/1055] Processing: p10085.RC.29.182.wav
[36/1055] Processing: p10085.RC.3.58.wav
[37/1055] Processing: p10085.RC.30.53.wav
[38/1055] Processing: p10085.RC.31.99999.wav
[39/1055] Processing: p10085.RC.32.24.wav
[40/1055] Processing: p10085.RC.33.126.wav
[41/1055] Processing: p10085.RC.34.18.wav
[42/1055] Processing: p10085.RC.35.75.wav
[43/1055] Processing: p10085.RC.36.99999.wav
[44/1055] Processing: p10085.RC.8.50.wav
[45/1055] Processing: p10085.RC.9.85.wav
[46/1055] Processing: p15965.LC.10.146.wav
[47/1055] Processing: p15965.LC.11.99999.wav
[48/1055] Processing: p15965.LC.12.161.wav
[49/1055] Processing: p15965.LC.13.83.wav
[50/1055] Processing: p15965.LC.14.48.wav
[51/1055] Processing: p15965.LC.15.182.wav
[52/1055] Processing: p15965.LC.17.164.wav
[53/1055] Processing: p15965.LC.18.143.wav
[54/1055] Processing: p15965.LC.19.131.wav
[55/1055] Processing: p15965.LC.2.118.wav
[56/1055] Processing: p15965.LC.20.10.wav
[57/1055] Processing: p15965.LC.21.99999.wav
[58/1055] Processing: p15965.LC.23.178.wav
[59/1055] Processing: p15965.LC.24.36.wav
[60/1055] Processing: p15965.LC.26.99999.wav
[61/1055] Processing: p15965.LC.29.1.wav
[62/1055] Processing: p15965.LC.3.45.wav
[63/1055] Processing: p15965.LC.30.123.wav
[64/1055] Processing: p15965.LC.31.99999.wav
[65/1055] Processing: p15965.LC.32.30.wav
[66/1055] Processing: p15965.LC.33.46.wav
[67/1055] Processing: p15965.LC.34.147.wav
[68/1055] Processing: p15965.LC.35.155.wav
[69/1055] Processing: p15965.LC.36.99999.wav
[70/1055] Processing: p15965.LC.38.63.wav
[71/1055] Processing: p15965.LC.4.81.wav
[72/1055] Processing: p15965.LC.41.99999.wav
[73/1055] Processing: p15965.LC.5.163.wav
[74/1055] Processing: p15965.LC.6.99999.wav
[75/1055] Processing: p15965.LC.7.66.wav
[76/1055] Processing: p15965.LC.9.129.wav
[77/1055] Processing: p15965.LW.11.99999.wav
[78/1055] Processing: p15965.LW.12.45.wav
[79/1055] Processing: p15965.LW.13.41.wav
[80/1055] Processing: p15965.LW.16.99999.wav
[81/1055] Processing: p15965.LW.17.134.wav
[82/1055] Processing: p15965.LW.18.118.wav
[83/1055] Processing: p15965.LW.19.67.wav
[84/1055] Processing: p15965.LW.2.155.wav
[85/1055] Processing: p15965.LW.20.63.wav
[86/1055] Processing: p15965.LW.21.99999.wav
[87/1055] Processing: p15965.LW.23.29.wav
[88/1055] Processing: p15965.LW.24.83.wav
[89/1055] Processing: p15965.LW.25.102.wav
[90/1055] Processing: p15965.LW.26.99999.wav
[91/1055] Processing: p15965.LW.27.36.wav
[92/1055] Processing: p15965.LW.28.69.wav
[93/1055] Processing: p15965.LW.3.122.wav
[94/1055] Processing: p15965.LW.30.163.wav
[95/1055] Processing: p15965.LW.31.99999.wav
[96/1055] Processing: p15965.LW.32.137.wav
[97/1055] Processing: p15965.LW.33.4.wav
[98/1055] Processing: p15965.LW.34.170.wav
[99/1055] Processing: p15965.LW.35.43.wav
[100/1055] Processing: p15965.LW.36.99999.wav
[101/1055] Processing: p15965.LW.37.138.wav
[102/1055] Processing: p15965.LW.38.47.wav
[103/1055] Processing: p15965.LW.39.65.wav
[104/1055] Processing: p15965.LW.4.116.wav
[105/1055] Processing: p15965.LW.40.95.wav
[106/1055] Processing: p15965.LW.41.99999.wav
[107/1055] Processing: p15965.LW.5.172.wav
[108/1055] Processing: p15965.LW.6.99999.wav
[109/1055] Processing: p15965.LW.7.153.wav
[110/1055] Processing: p15965.LW.8.32.wav
[111/1055] Processing: p15965.LW.9.160.wav
[112/1055] Processing: p15965.RC.1.44.wav
[113/1055] Processing: p15965.RC.10.155.wav
[114/1055] Processing: p15965.RC.11.99999.wav
[115/1055] Processing: p15965.RC.12.28.wav
[116/1055] Processing: p15965.RC.13.105.wav
[117/1055] Processing: p15965.RC.14.185.wav
[118/1055] Processing: p15965.RC.15.125.wav
[119/1055] Processing: p15965.RC.16.99999.wav
[120/1055] Processing: p15965.RC.17.47.wav
[121/1055] Processing: p15965.RC.18.56.wav
[122/1055] Processing: p15965.RC.19.31.wav
[123/1055] Processing: p15965.RC.2.121.wav
[124/1055] Processing: p15965.RC.20.99.wav
[125/1055] Processing: p15965.RC.21.99999.wav
[126/1055] Processing: p15965.RC.22.158.wav
[127/1055] Processing: p15965.RC.23.37.wav
[128/1055] Processing: p15965.RC.24.2.wav
[129/1055] Processing: p15965.RC.25.154.wav
[130/1055] Processing: p15965.RC.27.18.wav
[131/1055] Processing: p15965.RC.29.120.wav
[132/1055] Processing: p15965.RC.30.42.wav
[133/1055] Processing: p15965.RC.31.99999.wav
[134/1055] Processing: p15965.RC.32.76.wav
[135/1055] Processing: p15965.RC.33.104.wav
[136/1055] Processing: p15965.RC.34.39.wav
[137/1055] Processing: p15965.RC.35.72.wav
[138/1055] Processing: p15965.RC.36.99999.wav
[139/1055] Processing: p15965.RC.37.68.wav
[140/1055] Processing: p15965.RC.38.137.wav
[141/1055] Processing: p15965.RC.39.24.wav
[142/1055] Processing: p15965.RC.4.136.wav
[143/1055] Processing: p15965.RC.40.147.wav
[144/1055] Processing: p15965.RC.41.99999.wav
[145/1055] Processing: p15965.RC.5.53.wav
[146/1055] Processing: p15965.RC.6.99999.wav
[147/1055] Processing: p15965.RC.7.135.wav
[148/1055] Processing: p15965.RC.8.117.wav
[149/1055] Processing: p15965.RC.9.131.wav
[150/1055] Processing: p15965.RW.1.39.wav
[151/1055] Processing: p15965.RW.10.2.wav
[152/1055] Processing: p15965.RW.11.99999.wav
[153/1055] Processing: p15965.RW.12.61.wav
[154/1055] Processing: p15965.RW.13.180.wav
[155/1055] Processing: p15965.RW.14.112.wav
[156/1055] Processing: p15965.RW.15.106.wav
[157/1055] Processing: p15965.RW.17.183.wav
[158/1055] Processing: p15965.RW.18.151.wav
[159/1055] Processing: p15965.RW.19.140.wav
[160/1055] Processing: p15965.RW.2.181.wav
[161/1055] Processing: p15965.RW.20.161.wav
[162/1055] Processing: p15965.RW.21.99999.wav
[163/1055] Processing: p15965.RW.22.168.wav
[164/1055] Processing: p15965.RW.23.153.wav
[165/1055] Processing: p15965.RW.24.44.wav
[166/1055] Processing: p15965.RW.25.159.wav
[167/1055] Processing: p15965.RW.27.117.wav
[168/1055] Processing: p15965.RW.28.0.wav
[169/1055] Processing: p15965.RW.29.156.wav
[170/1055] Processing: p15965.RW.3.115.wav
[171/1055] Processing: p15965.RW.30.178.wav
[172/1055] Processing: p15965.RW.32.149.wav
[173/1055] Processing: p15965.RW.33.30.wav
[174/1055] Processing: p15965.RW.34.167.wav
[175/1055] Processing: p15965.RW.35.74.wav
[176/1055] Processing: p15965.RW.36.99999.wav
[177/1055] Processing: p15965.RW.37.67.wav
[178/1055] Processing: p15965.RW.38.76.wav
[179/1055] Processing: p15965.RW.39.137.wav
[180/1055] Processing: p15965.RW.4.68.wav
[181/1055] Processing: p15965.RW.40.107.wav
[182/1055] Processing: p15965.RW.41.99999.wav
[183/1055] Processing: p15965.RW.5.42.wav
[184/1055] Processing: p15965.RW.7.51.wav
[185/1055] Processing: p15965.RW.8.65.wav
[186/1055] Processing: p15965.RW.9.49.wav
[187/1055] Processing: p18785.LC.1.123.wav
[188/1055] Processing: p18785.LC.13.38.wav
[189/1055] Processing: p18785.LC.14.143.wav
[190/1055] Processing: p18785.LC.4.100.wav
[191/1055] Processing: p18785.LC.6.99999.wav
[192/1055] Processing: p18785.LC.7.13.wav
[193/1055] Processing: p18785.LC.8.175.wav
[194/1055] Processing: p18785.LW.11.99999.wav
[195/1055] Processing: p18785.LW.19.97.wav
[196/1055] Processing: p18785.LW.28.171.wav
[197/1055] Processing: p18785.RC.1.31.wav
[198/1055] Processing: p18785.RC.12.77.wav
[199/1055] Processing: p18785.RC.13.18.wav
[200/1055] Processing: p18785.RC.15.96.wav
[201/1055] Processing: p18785.RC.2.187.wav
[202/1055] Processing: p18785.RC.3.103.wav
[203/1055] Processing: p18785.RC.4.63.wav
[204/1055] Processing: p18785.RC.5.24.wav
[205/1055] Processing: p18785.RW.12.58.wav
[206/1055] Processing: p18785.RW.14.37.wav
[207/1055] Processing: p18785.RW.15.165.wav
[208/1055] Processing: p18785.RW.16.99999.wav
[209/1055] Processing: p18785.RW.19.131.wav
[210/1055] Processing: p18785.RW.21.99999.wav
[211/1055] Processing: p18785.RW.26.99999.wav
[212/1055] Processing: p18785.RW.28.102.wav
[213/1055] Processing: p18785.RW.9.5.wav
[214/1055] Processing: p20960.LC.1.185.wav
[215/1055] Processing: p20960.LC.11.99999.wav
[216/1055] Processing: p20960.LC.12.92.wav
[217/1055] Processing: p20960.LC.13.43.wav
[218/1055] Processing: p20960.LC.14.18.wav
[219/1055] Processing: p20960.LC.15.141.wav
[220/1055] Processing: p20960.LC.16.99999.wav
[221/1055] Processing: p20960.LC.19.6.wav
[222/1055] Processing: p20960.LC.2.84.wav
[223/1055] Processing: p20960.LC.20.120.wav
[224/1055] Processing: p20960.LC.23.37.wav
[225/1055] Processing: p20960.LC.24.25.wav
[226/1055] Processing: p20960.LC.27.140.wav
[227/1055] Processing: p20960.LC.28.83.wav
[228/1055] Processing: p20960.LC.29.182.wav
[229/1055] Processing: p20960.LC.3.40.wav
[230/1055] Processing: p20960.LC.30.128.wav
[231/1055] Processing: p20960.LC.31.99999.wav
[232/1055] Processing: p20960.LC.32.151.wav
[233/1055] Processing: p20960.LC.33.137.wav
[234/1055] Processing: p20960.LC.34.176.wav
[235/1055] Processing: p20960.LC.35.186.wav
[236/1055] Processing: p20960.LC.6.99999.wav
[237/1055] Processing: p20960.LC.7.1.wav
[238/1055] Processing: p20960.LW.19.31.wav
[239/1055] Processing: p20960.LW.5.165.wav
[240/1055] Processing: p20960.RC.13.88.wav
[241/1055] Processing: p20960.RC.16.99999.wav
[242/1055] Processing: p20960.RC.17.77.wav
[243/1055] Processing: p20960.RC.19.104.wav
[244/1055] Processing: p20960.RC.20.178.wav
[245/1055] Processing: p20960.RC.22.33.wav
[246/1055] Processing: p20960.RC.23.47.wav
[247/1055] Processing: p20960.RC.25.63.wav
[248/1055] Processing: p20960.RC.26.99999.wav
[249/1055] Processing: p20960.RC.27.56.wav
[250/1055] Processing: p20960.RC.28.58.wav
[251/1055] Processing: p20960.RC.30.143.wav
[252/1055] Processing: p20960.RC.31.99999.wav
[253/1055] Processing: p20960.RC.32.109.wav
[254/1055] Processing: p20960.RC.33.22.wav
[255/1055] Processing: p20960.RC.35.121.wav
[256/1055] Processing: p20960.RC.5.16.wav
[257/1055] Processing: p20960.RC.7.142.wav
[258/1055] Processing: p20960.RW.10.17.wav
[259/1055] Processing: p20960.RW.25.88.wav
[260/1055] Processing: p20960.RW.4.185.wav
[261/1055] Processing: p28030.LC.10.63.wav
[262/1055] Processing: p28030.LC.2.59.wav
[263/1055] Processing: p28030.LC.20.17.wav
[264/1055] Processing: p28030.LC.3.133.wav
[265/1055] Processing: p28030.LC.31.99999.wav
[266/1055] Processing: p28030.LC.5.23.wav
[267/1055] Processing: p28030.LC.7.86.wav
[268/1055] Processing: p28030.LC.8.188.wav
[269/1055] Processing: p28030.LC.9.12.wav
[270/1055] Processing: p28030.LW.15.107.wav
[271/1055] Processing: p28030.LW.16.99999.wav
[272/1055] Processing: p28030.LW.18.53.wav
[273/1055] Processing: p28030.LW.20.50.wav
[274/1055] Processing: p28030.RC.1.86.wav
[275/1055] Processing: p28030.RC.13.22.wav
[276/1055] Processing: p28030.RC.18.45.wav
[277/1055] Processing: p28030.RC.19.51.wav
[278/1055] Processing: p28030.RC.26.99999.wav
[279/1055] Processing: p28030.RC.29.39.wav
[280/1055] Processing: p28030.RC.3.7.wav
[281/1055] Processing: p28030.RC.30.118.wav
[282/1055] Processing: p28030.RC.33.152.wav
[283/1055] Processing: p28030.RC.36.99999.wav
[284/1055] Processing: p28030.RC.4.66.wav
[285/1055] Processing: p28030.RC.5.178.wav
[286/1055] Processing: p28030.RC.6.99999.wav
[287/1055] Processing: p28030.RW.13.175.wav
[288/1055] Processing: p28030.RW.16.99999.wav
[289/1055] Processing: p28030.RW.28.177.wav
[290/1055] Processing: p37540.LC.10.24.wav
[291/1055] Processing: p37540.LC.14.32.wav
[292/1055] Processing: p37540.LC.15.185.wav
[293/1055] Processing: p37540.LC.17.128.wav
[294/1055] Processing: p37540.LC.2.16.wav
[295/1055] Processing: p37540.LC.20.67.wav
[296/1055] Processing: p37540.LC.25.121.wav
[297/1055] Processing: p37540.LC.29.87.wav
[298/1055] Processing: p37540.LC.31.99999.wav
[299/1055] Processing: p37540.LC.33.166.wav
[300/1055] Processing: p37540.LC.34.30.wav
[301/1055] Processing: p37540.LC.35.48.wav
[302/1055] Processing: p37540.LC.36.99999.wav
[303/1055] Processing: p37540.LC.4.90.wav
[304/1055] Processing: p37540.LC.9.112.wav
[305/1055] Processing: p37540.LW.15.168.wav
[306/1055] Processing: p37540.LW.21.99999.wav
[307/1055] Processing: p37540.RC.11.99999.wav
[308/1055] Processing: p37540.RC.16.99999.wav
[309/1055] Processing: p37540.RC.17.131.wav
[310/1055] Processing: p37540.RC.18.186.wav
[311/1055] Processing: p37540.RC.21.99999.wav
[312/1055] Processing: p37540.RC.22.138.wav
[313/1055] Processing: p37540.RC.27.35.wav
[314/1055] Processing: p37540.RC.28.187.wav
[315/1055] Processing: p37540.RC.29.154.wav
[316/1055] Processing: p37540.RC.3.182.wav
[317/1055] Processing: p37540.RC.30.91.wav
[318/1055] Processing: p37540.RC.31.99999.wav
[319/1055] Processing: p37540.RC.32.119.wav
[320/1055] Processing: p37540.RC.33.93.wav
[321/1055] Processing: p37540.RC.36.99999.wav
[322/1055] Processing: p37540.RC.4.36.wav
[323/1055] Processing: p37540.RC.5.89.wav
[324/1055] Processing: p37540.RW.10.18.wav
[325/1055] Processing: p37540.RW.13.0.wav
[326/1055] Processing: p37540.RW.16.99999.wav
[327/1055] Processing: p37540.RW.25.135.wav
[328/1055] Processing: p37540.RW.36.99999.wav
[329/1055] Processing: p37540.RW.6.99999.wav
[330/1055] Processing: p37540.RW.8.104.wav
[331/1055] Processing: p59520.LC.1.148.wav
[332/1055] Processing: p59520.LC.10.66.wav
[333/1055] Processing: p59520.LC.12.181.wav
[334/1055] Processing: p59520.LC.13.107.wav
[335/1055] Processing: p59520.LC.14.153.wav
[336/1055] Processing: p59520.LC.15.47.wav
[337/1055] Processing: p59520.LC.16.99999.wav
[338/1055] Processing: p59520.LC.19.101.wav
[339/1055] Processing: p59520.LC.2.60.wav
[340/1055] Processing: p59520.LC.20.177.wav
[341/1055] Processing: p59520.LC.22.152.wav
[342/1055] Processing: p59520.LC.27.33.wav
[343/1055] Processing: p59520.LC.29.63.wav
[344/1055] Processing: p59520.LC.3.86.wav
[345/1055] Processing: p59520.LC.30.114.wav
[346/1055] Processing: p59520.LC.36.99999.wav
[347/1055] Processing: p59520.LC.4.137.wav
[348/1055] Processing: p59520.LC.5.140.wav
[349/1055] Processing: p59520.LC.6.99999.wav
[350/1055] Processing: p59520.LC.7.186.wav
[351/1055] Processing: p59520.LW.14.72.wav
[352/1055] Processing: p59520.LW.19.184.wav
[353/1055] Processing: p59520.LW.35.136.wav
[354/1055] Processing: p59520.LW.8.17.wav
[355/1055] Processing: p59520.RC.1.121.wav
[356/1055] Processing: p59520.RC.11.99999.wav
[357/1055] Processing: p59520.RC.12.8.wav
[358/1055] Processing: p59520.RC.14.162.wav
[359/1055] Processing: p59520.RC.19.56.wav
[360/1055] Processing: p59520.RC.2.156.wav
[361/1055] Processing: p59520.RC.21.99999.wav
[362/1055] Processing: p59520.RC.22.10.wav
[363/1055] Processing: p59520.RC.23.34.wav
[364/1055] Processing: p59520.RC.24.58.wav
[365/1055] Processing: p59520.RC.25.126.wav
[366/1055] Processing: p59520.RC.26.99999.wav
[367/1055] Processing: p59520.RC.28.57.wav
[368/1055] Processing: p59520.RC.29.184.wav
[369/1055] Processing: p59520.RC.3.13.wav
[370/1055] Processing: p59520.RC.32.30.wav
[371/1055] Processing: p59520.RC.33.71.wav
[372/1055] Processing: p59520.RC.34.174.wav
[373/1055] Processing: p59520.RC.35.76.wav
[374/1055] Processing: p59520.RC.36.99999.wav
[375/1055] Processing: p59520.RC.4.47.wav
[376/1055] Processing: p59520.RC.5.112.wav
[377/1055] Processing: p59520.RC.7.95.wav
[378/1055] Processing: p59520.RC.9.166.wav
[379/1055] Processing: p59520.RW.16.99999.wav
[380/1055] Processing: p59520.RW.24.130.wav
[381/1055] Processing: p59520.RW.25.79.wav
[382/1055] Processing: p59520.RW.3.66.wav
[383/1055] Processing: p59520.RW.34.156.wav
[384/1055] Processing: p59520.RW.6.99999.wav
[385/1055] Processing: p60145.LC.11.99999.wav
[386/1055] Processing: p60145.LC.12.31.wav
[387/1055] Processing: p60145.LC.14.50.wav
[388/1055] Processing: p60145.LC.15.147.wav
[389/1055] Processing: p60145.LC.16.99999.wav
[390/1055] Processing: p60145.LC.17.32.wav
[391/1055] Processing: p60145.LC.21.99999.wav
[392/1055] Processing: p60145.LC.22.104.wav
[393/1055] Processing: p60145.LC.23.169.wav
[394/1055] Processing: p60145.LC.25.173.wav
[395/1055] Processing: p60145.LC.26.99999.wav
[396/1055] Processing: p60145.LC.28.175.wav
[397/1055] Processing: p60145.LC.32.53.wav
[398/1055] Processing: p60145.LC.33.40.wav
[399/1055] Processing: p60145.LC.34.30.wav
[400/1055] Processing: p60145.LC.35.92.wav
[401/1055] Processing: p60145.LC.36.99999.wav
[402/1055] Processing: p60145.LC.37.33.wav
[403/1055] Processing: p60145.LC.39.28.wav
[404/1055] Processing: p60145.LC.4.131.wav
[405/1055] Processing: p60145.LC.7.119.wav
[406/1055] Processing: p60145.LW.11.99999.wav
[407/1055] Processing: p60145.LW.23.57.wav
[408/1055] Processing: p60145.LW.27.18.wav
[409/1055] Processing: p60145.LW.31.99999.wav
[410/1055] Processing: p60145.RC.11.99999.wav
[411/1055] Processing: p60145.RC.14.162.wav
[412/1055] Processing: p60145.RC.19.35.wav
[413/1055] Processing: p60145.RC.20.90.wav
[414/1055] Processing: p60145.RC.21.99999.wav
[415/1055] Processing: p60145.RC.22.97.wav
[416/1055] Processing: p60145.RC.23.123.wav
[417/1055] Processing: p60145.RC.24.113.wav
[418/1055] Processing: p60145.RC.25.61.wav
[419/1055] Processing: p60145.RC.26.99999.wav
[420/1055] Processing: p60145.RC.27.136.wav
[421/1055] Processing: p60145.RC.28.58.wav
[422/1055] Processing: p60145.RC.3.18.wav
[423/1055] Processing: p60145.RC.30.78.wav
[424/1055] Processing: p60145.RC.33.34.wav
[425/1055] Processing: p60145.RC.35.39.wav
[426/1055] Processing: p60145.RC.36.99999.wav
[427/1055] Processing: p60145.RC.8.3.wav
[428/1055] Processing: p60145.RC.9.8.wav
[429/1055] Processing: p60145.RW.10.123.wav
[430/1055] Processing: p60145.RW.12.145.wav
[431/1055] Processing: p60145.RW.19.172.wav
[432/1055] Processing: p60145.RW.2.160.wav
[433/1055] Processing: p60145.RW.27.32.wav
[434/1055] Processing: p60145.RW.29.154.wav
[435/1055] Processing: p60145.RW.34.100.wav
[436/1055] Processing: p60145.RW.41.99999.wav
[437/1055] Processing: p62650.LW.11.99999.wav
[438/1055] Processing: p62650.LW.16.99999.wav
[439/1055] Processing: p62650.LW.2.99.wav
[440/1055] Processing: p62650.LW.26.99999.wav
[441/1055] Processing: p62650.LW.30.86.wav
[442/1055] Processing: p62650.RC.1.165.wav
[443/1055] Processing: p62650.RC.10.47.wav
[444/1055] Processing: p62650.RC.11.99999.wav
[445/1055] Processing: p62650.RC.12.26.wav
[446/1055] Processing: p62650.RC.14.6.wav
[447/1055] Processing: p62650.RC.16.99999.wav
[448/1055] Processing: p62650.RC.17.60.wav
[449/1055] Processing: p62650.RC.18.48.wav
[450/1055] Processing: p62650.RC.19.180.wav
[451/1055] Processing: p62650.RC.2.125.wav
[452/1055] Processing: p62650.RC.20.42.wav
[453/1055] Processing: p62650.RC.21.99999.wav
[454/1055] Processing: p62650.RC.23.101.wav
[455/1055] Processing: p62650.RC.24.51.wav
[456/1055] Processing: p62650.RC.25.46.wav
[457/1055] Processing: p62650.RC.26.99999.wav
[458/1055] Processing: p62650.RC.27.34.wav

,participant_id,filename,file_path,name,frameTime,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,p10085,p10085.LC.1.161.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.1.161.wav,0.0,35.01984,0.058435,32.85135,34.98690,36.56286,...,-0.026313,-0.016247,0.194337,3.759399,3.065134,0.107500,0.047368,0.175556,0.172118,-28.58768
1,p10085,p10085.LC.12.59.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.12.59.wav,0.0,36.45980,0.054268,35.04674,35.46410,38.76045,...,-0.026646,-0.012436,0.188892,4.245283,2.415459,0.140000,0.077974,0.254000,0.238462,-27.72683
2,p10085,p10085.LC.14.45.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.14.45.wav,0.0,34.32713,0.041927,33.18588,33.72220,35.32593,...,-0.029667,-0.014263,0.194797,3.524229,2.252252,0.196000,0.151737,0.226000,0.256094,-28.09820
3,p10085,p10085.LC.18.41.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.18.41.wav,0.0,34.30873,0.110540,33.53381,34.41000,36.70712,...,-0.018814,-0.020257,0.184749,4.017857,3.196347,0.127143,0.137811,0.165714,0.139577,-29.13141
4,p10085,p10085.LC.2.106.wav,C:\Users\marti\Documents\Technical Medicine Ma...,p10085.LC.2.106.wav,0.0,35.14960,0.062773,33.52357,34.20152,37.36135,...,-0.028444,-0.013930,0.167088,2.966102,2.164502,0.180000,0.093595,0.258000,0.288056,-27.76791